## Different models

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 56.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 28.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 92.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.9 MB/s eta 0:00:00


In [ ]:
!pip install sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 25.3 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125926 sha256=1ca17cd9a67b5e2b85fd29d97ab0b5a597327d1c4b98dcdca56b489f7da05cd6
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L12-v2')  # https://www.sbert.net/docs/pretrained_models.html
embeddings = model.encode(sentences)
print(embeddings)

[[-2.02690993e-04  8.14801678e-02  3.13618146e-02  2.92058010e-03
   2.61564348e-02  2.90739797e-02  7.82618746e-02 -1.80415739e-03
   1.01344280e-01 -4.51711826e-02  5.84349744e-02 -1.53200831e-02
   5.49956486e-02 -9.86434743e-02 -3.50252688e-02  8.45676754e-03
   1.58609059e-02  1.05627142e-02 -3.42710242e-02 -4.75066341e-03
   9.99021083e-02 -2.06018183e-02 -4.47837375e-02  3.12135890e-02
  -1.19241169e-02 -5.15015498e-02 -1.33605739e-02  1.89621132e-02
   9.76810381e-02 -5.44110611e-02 -3.43313776e-02  8.12905505e-02
   4.88119908e-02 -1.10284006e-02  2.13519298e-02  1.27189597e-02
  -1.43967802e-02  3.62864472e-02 -7.61233494e-02  3.23294215e-02
   2.08102055e-02 -4.22016196e-02  9.12906900e-02  2.08529830e-02
  -3.08016986e-02 -8.38505477e-02  1.30890738e-02 -3.00631542e-02
   4.11228612e-02 -1.27495319e-01 -7.78027177e-02 -3.93412262e-02
   1.52600487e-03 -2.80108023e-02  3.41662578e-02  1.46712577e-02
  -7.71653578e-02  1.63619533e-01  4.11294773e-02 -5.24460413e-02
  -4.18771

In [ ]:
len(embeddings)

2

In [ ]:
len(embeddings[0])

384

In [ ]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('prajjwal1/bert-tiny')  # https://huggingface.co/prajjwal1/bert-tiny
embeddings = model.encode(sentences)
print(embeddings)

Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/prajjwal1_bert-tiny were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[[-1.78319228e+00 -1.95020631e-01 -6.39198005e-01 -1.54961789e+00
  -4.36085552e-01  8.33339036e-01  2.09940985e-01  1.91608761e-02
  -2.47738242e-01  1.43931523e-01 -1.52925178e-01  5.38572073e-01
  -8.15969348e-01 -1.94766536e-01  1.74845505e+00 -9.91718709e-01
  -2.37336659e+00  2.55672298e-02 -2.88146466e-01  1.64576158e-01
   2.96085507e-01 -8.88109028e-01  1.93792152e+00  7.49644935e-01
   2.17490172e+00 -7.60114729e-01  3.12099248e-01  9.25262392e-01
   1.91842485e-02 -5.99868238e-01 -1.86730313e+00 -3.76728117e-01
  -6.75430417e-01  9.70788956e-01 -5.14764726e-01  4.04827967e-02
   4.70572531e-01 -2.85376251e-01 -9.75075603e-01 -7.16268539e-01
  -3.06999862e-01  2.79383004e-01  5.87477803e-01 -1.16913259e+00
  -8.04785863e-02 -1.27408791e+00 -7.72162303e-02  2.25843266e-01
   7.26560295e-01  2.20282927e-01  7.52272248e-01  1.27413785e+00
  -7.25243092e-02 -5.82517564e-01 -6.56688571e-01 -5.14837086e-01
   5.53133607e-01 -6.72846913e-01  4.06058095e-02  2.65048099e+00
   1.27951

In [ ]:
len(embeddings[0])

128

In [ ]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('haisongzhang/roberta-tiny-cased')  # https://huggingface.co/haisongzhang/roberta-tiny-cased
embeddings = model.encode(sentences)
print(embeddings)

[[ 0.18938926  0.19803585 -0.02020433 ...  0.45603117 -0.11738718
   0.02220043]
 [-0.01708825 -0.44656798 -0.31965017 ...  0.84217435 -0.12856944
  -0.02648142]]


In [ ]:
len(embeddings[0])

512

In [ ]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('smallbenchnlp/roberta-small')  # https://huggingface.co/smallbenchnlp/roberta-small
embeddings = model.encode(sentences)
print(embeddings)

Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/smallbenchnlp_roberta-small were not used when initializing RobertaModel: ['lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at /root/.cache/torch/sentence_transformers/smallbenchnlp_roberta-small and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this 

[[ 9.00972545e-01 -6.02666080e-01  1.29254079e+00  1.23360261e-01
   7.72032320e-01 -1.11916864e+00  5.22864878e-01 -4.78740394e-01
   2.33392701e-01 -4.23416644e-01  4.11070436e-01 -7.14469135e-01
   8.36952150e-01  4.68886107e-01 -2.96202123e-01  9.92351890e-01
   7.96355680e-02 -1.11525726e+00 -1.41339111e+00 -1.62718982e-01
   5.22364303e-02  1.75290450e-01 -2.19632387e-01  2.06121635e+00
   3.91695797e-01 -1.81338802e-01  3.55559438e-01 -1.20966780e+00
  -7.06581652e-01 -2.13415965e-01 -6.50910378e-01 -7.07516193e-01
  -4.07720983e-01  4.88919109e-01 -1.15076542e+00 -1.94115365e+00
  -3.92349958e-01  1.88852525e+00 -2.95186698e-01 -9.01338458e-01
  -4.49103266e-01  1.22203596e-01 -5.82414687e-01  1.84115797e-01
   2.57323295e-01 -8.84790361e-01  2.07417682e-01 -9.52572286e-01
  -5.87589800e-01 -2.46412158e-01 -5.49859881e-01  2.22603187e-01
   1.16379984e-01  5.01187682e-01  9.40324485e-01 -1.06551743e+00
   4.53313142e-01 -5.30231357e-01  4.07714814e-01  1.46834064e+00
   5.08297

In [ ]:
len(embeddings[0])

256

## U-MAP

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [ ]:
pickle_in = open("/content/drive/MyDrive/IDSIA Biomedical Texts/Reddit_alldistilrobertav1_sentenceembeddings.pickle", 'rb')
sentence_embeddings = pickle.load(pickle_in)
sentence_embeddings

# Note 18th Sept - I had gotten sentence_embeddings for all sources, quora, and reddit in this very same code in this error, thats why rihgt now it shows i am importing reeddit embeddings, but i had done all sources first, then quora and then lastly this

array([[-0.04389209, -0.00029614,  0.07935358, ..., -0.00547486,
         0.00226794,  0.01068765],
       [-0.00047695,  0.02604182,  0.03328595, ...,  0.07153162,
         0.01115347,  0.00922567],
       [-0.01490259, -0.02341347,  0.01380358, ..., -0.00907313,
         0.01289819, -0.0381882 ],
       ...,
       [-0.03207999,  0.03539538,  0.01939519, ...,  0.05209309,
         0.04038427, -0.03257773],
       [-0.03034277,  0.01156614,  0.00162231, ...,  0.02362805,
         0.01977406,  0.00862481],
       [-0.02173869,  0.04743871,  0.00477439, ...,  0.0474075 ,
         0.04885022, -0.01362175]], dtype=float32)

In [ ]:
sentence_embeddings.shape

(505, 768)

In [ ]:
!pip install umap-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 24.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.3-py3-none-any.whl size=82816 sha256=18540c6867b04fa70277f9772d51b1fbcd7a222455121f8ba34ff1ad08619e92
  Stored in directory: /root/.cache/pip/wheels/a0/e8/c6/a37ea663620bd5200ea1ba0907ab3c217042c1d035ef606acc
  Created wheel for pynndescent: filename=pynndescent-0.5.10-py3-none-any.whl size=55622 sha256=4e2cf2c4228b918ec8b9073f9cb8daa09b14f1e7d5e832871645655f9c3ffd4a
  Stored in directory: /root/.cache/pip/wheels/4a/38/5d/f60a40a66a9512b7e5e83517ebc2d1b42d857be97d135f1096
Successfully built umap-learn pynndescent


In [ ]:
import umap.umap_ as umap

In [ ]:
# Perform U-Map dimensionality reduction
reducer = umap.UMAP(n_components=28)  # Reduce to 28 dimensions
short_embedding_28 = reducer.fit_transform(sentence_embeddings)

In [ ]:
# from matplotlib.colors import ListedColormap

# plt.figure(figsize=(20, 8))

# # Define colors for labels 0 and 1
# colors = ['red', 'blue']

# # Create a custom colormap
# cmap = ListedColormap(colors)

# # Plot the U-Map graph
# plt.scatter(short_embedding_28[:, 0], short_embedding_28[:, 1], c=df['label'])
# plt.colorbar()
# plt.show()
# #1 for panic, 0 for anxiety

In [ ]:
# pickle_out = open("Reddit_alldistilrobertav1_via_UMAP_SHORTembeddings.pickle", 'wb')
# pickle.dump(short_embedding_28, pickle_out)
# pickle_out.close()

In [ ]:
short_embedding_28

array([[10.64194  ,  5.0430765,  5.6824026, ...,  4.9058275,  6.8707986,
         4.538727 ],
       [11.312859 ,  5.364349 ,  4.41365  , ...,  4.92234  ,  6.8475184,
         4.5590596],
       [10.531799 ,  4.894456 ,  5.387705 , ...,  4.8968716,  6.8360796,
         4.530069 ],
       ...,
       [10.346373 ,  4.4247556,  3.5815325, ...,  5.0401225,  6.552696 ,
         4.490976 ],
       [10.454275 ,  4.5640407,  3.6035635, ...,  5.0320673,  6.564847 ,
         4.4918733],
       [11.222271 ,  5.1468487,  4.0054016, ...,  5.079988 ,  6.6341186,
         4.5597043]], dtype=float32)

In [ ]:
len(short_embedding_28)

7405

In [ ]:
len(short_embedding_28[0])

28

In [ ]:
short_embedding_28[0]

array([10.64194  ,  5.0430765,  5.6824026,  3.3668725,  3.9393306,
        3.919311 ,  6.9191246,  1.7899821,  1.4046252,  7.134058 ,
        4.420479 ,  7.684002 ,  2.286182 ,  2.857458 ,  2.669546 ,
        4.379669 ,  3.859759 ,  5.4032583,  6.754729 ,  4.308768 ,
        2.2254827,  3.1967173,  5.9695396,  5.9377785,  5.1765523,
        4.9058275,  6.8707986,  4.538727 ], dtype=float32)

In [ ]:
short_embedding_28[1]

array([11.312859 ,  5.364349 ,  4.41365  ,  3.407885 ,  5.0235395,
        4.24744  ,  6.0880933,  1.7800032,  1.160577 ,  6.5965633,
        4.065295 ,  7.592488 ,  2.1721222,  3.1727264,  2.6803257,
        4.2805276,  3.7960715,  5.6547985,  7.253571 ,  4.0705576,
        2.360492 ,  3.1813912,  6.144005 ,  5.6629734,  5.0732694,
        4.92234  ,  6.8475184,  4.5590596], dtype=float32)

## Logistic Regression and XGBoost

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [ ]:
# Whole dataset
pickle_in = open("/content/drive/MyDrive/IDSIA Biomedical Texts/AllSourceEmotions_TwentyJune.pickle", 'rb')
df = pickle.load(pickle_in)
df.head(1)

# # Quora data
# df = df[df['source'] == 'Quora']
# df.reset_index(drop=True, inplace=True)
# df.head(1)

# # Reddit data
# df = df[df['source'] == 'Reddit']
# df.reset_index(drop=True, inplace=True)
# df.head(1)

urls  \
0  https://www.quora.com/What-are-panic-attacks-l...   

                                                text source  label   WC  \
0  I have been dealing with these for quite some ...  Quora      1  607   

   Analytic  Clout  Authentic  Tone    WPS  ...     pride  realization  \
0     55.22  35.35      48.82   1.0  26.39  ...  0.000041     0.000323   

     relief  remorse   sadness  surprise   neutral  \
0  0.001267  0.00033  0.000575  0.000205  0.000843   

                                    all_emolabelprob  \
0  [(fear, 0.8543168), (nervousness, 0.068863705)...   

                                      all_emo_labels  \
0  [fear, nervousness, confusion, curiosity, cari...   

                                  all_emo_label_rank  
0  {'fear': 1, 'nervousness': 2, 'confusion': 3, ...  

[1 rows x 157 columns]

In [ ]:
# Whole
pickle_in = open("/content/drive/MyDrive/IDSIA Biomedical Texts/Sentence Embeddings/AllSource_alldistilrobertav1_via_UMAP_SHORTembeddings.pickle", 'rb')
sentence_embeddings = pickle.load(pickle_in)
sentence_embeddings

# # Quora
# pickle_in = open("/content/drive/MyDrive/IDSIA Biomedical Texts/Sentence Embeddings/Quora_alldistilrobertav1_via_UMAP_SHORTembeddings.pickle", 'rb')
# sentence_embeddings = pickle.load(pickle_in)
# sentence_embeddings

# # Reddit
# pickle_in = open("/content/drive/MyDrive/IDSIA Biomedical Texts/Sentence Embeddings/Reddit_alldistilrobertav1_via_UMAP_SHORTembeddings.pickle", 'rb')
# sentence_embeddings = pickle.load(pickle_in)
# sentence_embeddings

array([[10.64194  ,  5.0430765,  5.6824026, ...,  4.9058275,  6.8707986,
         4.538727 ],
       [11.312859 ,  5.364349 ,  4.41365  , ...,  4.92234  ,  6.8475184,
         4.5590596],
       [10.531799 ,  4.894456 ,  5.387705 , ...,  4.8968716,  6.8360796,
         4.530069 ],
       ...,
       [10.346373 ,  4.4247556,  3.5815325, ...,  5.0401225,  6.552696 ,
         4.490976 ],
       [10.454275 ,  4.5640407,  3.6035635, ...,  5.0320673,  6.564847 ,
         4.4918733],
       [11.222271 ,  5.1468487,  4.0054016, ...,  5.079988 ,  6.6341186,
         4.5597043]], dtype=float32)

In [ ]:
sentence_embeddings.shape

(7405, 28)

In [ ]:
# Normalize sentence embeddings so that all values are between 0 and 1 (becasue emotions features are between 0 and 1 too)
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler(feature_range=(0,1))  # (0,1) is default

In [ ]:
# This is wrong because it is computing min and max column wise (so total 28 computations are made), not in the row for the whole array (so that 7405 computation are made and min/max is calculated for 28 elements in each row)

# sentence_embeddings = scaling.fit_transform(sentence_embeddings)
# sentence_embeddings

In [ ]:
sentence_embeddings = scaling.fit_transform(sentence_embeddings.reshape(-1, 1)).reshape(*sentence_embeddings.shape) # https://stackoverflow.com/questions/75461346/different-result-from-minmaxscaler-with-manual-calculations
sentence_embeddings

array([[0.8199141 , 0.35134387, 0.40484923, ..., 0.33985746, 0.5043063 ,
        0.30913472],
       [0.8760634 , 0.37823123, 0.298667  , ..., 0.3412394 , 0.502358  ,
        0.31083637],
       [0.81069636, 0.33890578, 0.3801859 , ..., 0.33910793, 0.5014007 ,
        0.30841014],
       ...,
       [0.795178  , 0.29959643, 0.22902691, ..., 0.35109666, 0.4776843 ,
        0.30513844],
       [0.80420834, 0.31125325, 0.2308707 , ..., 0.3504225 , 0.4787012 ,
        0.30521354],
       [0.8684821 , 0.3600286 , 0.26450062, ..., 0.354433  , 0.4844986 ,
        0.31089035]], dtype=float32)

In [ ]:
sentence_embeddings.shape

(7405, 28)

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import xgboost as xgb
from sklearn.metrics import roc_auc_score, make_scorer # not able to import balanced_accuray_score
from sklearn.model_selection import GridSearchCV # cross validation, used for hyperparamter tuning
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve, auc

In [ ]:
df.loc[:, 'admiration':'neutral']

admiration  amusement     anger  annoyance  approval    caring  \
0       0.000016   0.000150  0.000705   0.001447  0.000643  0.009114   
1       0.000054   0.167888  0.011522   0.201494  0.000443  0.001504   
2       0.000101   0.000596  0.000428   0.001275  0.006295  0.013178   
3       0.000054   0.000639  0.043696   0.003672  0.000041  0.007463   
4       0.000004   0.000040  0.000176   0.000860  0.000181  0.000255   
...          ...        ...       ...        ...       ...       ...   
7400    0.000907   0.000017  0.000027   0.000027  0.000360  0.001514   
7401    0.000451   0.000075  0.000005   0.000022  0.000736  0.000157   
7402    0.000228   0.000024  0.000010   0.000034  0.000405  0.000364   
7403    0.000064   0.000080  0.000109   0.000155  0.012040  0.932658   
7404    0.003813   0.000036  0.000079   0.000095  0.039129  0.920536   

      confusion  curiosity    desire  disappointment  ...      love  \
0      0.048850   0.010012  0.000057        0.000440  ...  0.000210   
1      0.002532   0.000539  0.000486        0.053486  ...  0.003212   
2      0.412494   0.034596  0.000124        0.002020  ...  0.001481   
3      0.000333   0.000094  0.000294        0.002422  ...  0.005427   
4      0.001674   0.000182  0.000016        0.001535  ...  0.000145   
...         ...        ...       ...             ...  ...       ...   
7400   0.000162   0.000076  0.000035        0.000038  ...  0.000018   
7401   0.000070   0.000227  0.000052        0.000015  ...  0.000010   
7402   0.000123   0.000703  0.000040        0.000015  ...  0.000008   
7403   0.000593   0.001206  0.000311        0.000126  ...  0.000124   
7404   0.000142   0.000082  0.000070        0.000138  ...  0.000231   

      nervousness  optimism     pride  realization    relief   remorse  \
0        0.068864  0.000185  0.000041     0.000323  0.001267  0.000330   
1        0.013415  0.000246  0.000617     0.022932  0.000231  0.003261   
2        0.035853  0.000615  0.000224     0.336612  0.002241  0.001373   
3        0.010949  0.000076  0.000740     0.000619  0.000275  0.001561   
4        0.079422  0.000020  0.000017     0.000338  0.000211  0.000071   
...           ...       ...       ...          ...       ...       ...   
7400     0.000038  0.000060  0.000021     0.000021  0.000448  0.000136   
7401     0.000004  0.000037  0.000003     0.000018  0.000051  0.000023   
7402     0.000007  0.000077  0.000003     0.000009  0.000134  0.000023   
7403     0.016793  0.015985  0.000026     0.000285  0.005689  0.000256   
7404     0.000211  0.007032  0.000072     0.001102  0.007063  0.000425   

       sadness  surprise   neutral  
0     0.000575  0.000205  0.000843  
1     0.416074  0.001216  0.003240  
2     0.007805  0.013074  0.041802  
3     0.057985  0.000332  0.000073  
4     0.002956  0.000103  0.000174  
...        ...       ...       ...  
7400  0.000022  0.000016  0.000068  
7401  0.000008  0.000011  0.001105  
7402  0.000008  0.000013  0.000393  
7403  0.000404  0.000174  0.003708  
7404  0.000141  0.000089  0.015839  

[7405 rows x 28 columns]

In [ ]:
# Short Sentence Embeddings, and Short Embeddings+emotions

#X = sentence_embeddings
X = np.concatenate((df.loc[:, 'admiration':'neutral'] , sentence_embeddings), axis=1)
y = df['label']

In [ ]:
X

array([[1.6097219e-05, 1.5009375e-04, 7.0454186e-04, ..., 3.3985746e-01,
        5.0430632e-01, 3.0913472e-01],
       [5.3580854e-05, 1.6788803e-01, 1.1522046e-02, ..., 3.4123939e-01,
        5.0235802e-01, 3.1083637e-01],
       [1.0068560e-04, 5.9565360e-04, 4.2768064e-04, ..., 3.3910793e-01,
        5.0140071e-01, 3.0841014e-01],
       ...,
       [2.2835303e-04, 2.3706596e-05, 1.0201779e-05, ..., 3.5109666e-01,
        4.7768429e-01, 3.0513844e-01],
       [6.4288128e-05, 8.0106511e-05, 1.0939107e-04, ..., 3.5042250e-01,
        4.7870120e-01, 3.0521354e-01],
       [3.8129615e-03, 3.6401994e-05, 7.9194528e-05, ..., 3.5443300e-01,
        4.8449859e-01, 3.1089035e-01]], dtype=float32)

In [ ]:
X.shape

(7405, 56)

In [ ]:
clf = LogisticRegression(solver='lbfgs', max_iter=11000)
clf_xgb = xgb.XGBClassifier(objective='binary:logistic', missing=0, seed=42) # missing=None not working

In [ ]:
logistic_f1scores = []
logistic_rocaucscore = []
logistic_praucscore = []
xgb_f1scores = []
xgb_rocaucscore = []
xgb_praucscore = []

for train_index, test_index in folds.split(X, y):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]

    # Logistic
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    f1 = f1_score(y_test, y_pred,average='weighted')
    logistic_f1scores.append(f1)
    rocaucscore = roc_auc_score(y_test, y_pred)
    logistic_rocaucscore.append(rocaucscore)
    precision, recall, thresholds = precision_recall_curve(y_test, y_pred)  # Compute precision, recall, and thresholds
    pr_auc = auc(recall, precision)  # Calculate PR-AUC
    logistic_praucscore.append(pr_auc)

    # XGBoost
    clf_xgb.fit(X_train, y_train,
              verbose=False,  # set to True for individual use
              early_stopping_rounds=10,
              #eval_metrics='aucpr',
              eval_set = [(X_test,y_test)])
    y_pred = clf_xgb.predict(X_test)
    f1 = f1_score(y_test, y_pred,average='weighted')
    xgb_f1scores.append(f1)
    rocaucscore = roc_auc_score(y_test, y_pred)
    xgb_rocaucscore.append(rocaucscore)
    precision, recall, thresholds = precision_recall_curve(y_test, y_pred)  # Compute precision, recall, and thresholds
    pr_auc = auc(recall, precision)  # Calculate PR-AUC
    xgb_praucscore.append(pr_auc)

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`se

In [ ]:
print(logistic_f1scores)
print(np.mean(logistic_f1scores))
print(np.std(logistic_f1scores))

[0.86431972352435, 0.8357337121718914, 0.8735243512504244, 0.8563903179587831, 0.8592656466340675, 0.8531125864037576, 0.8519438529458266, 0.8560794837390582, 0.8620663894997816, 0.8549015320738877]
0.8567337596201827
0.009248131649476183


In [ ]:
print(logistic_rocaucscore)
print(np.mean(logistic_rocaucscore))
print(np.std(logistic_rocaucscore))

[0.8445786132204656, 0.8201442487240135, 0.8590462778538529, 0.8373856280343583, 0.8409957363376073, 0.8381121939030485, 0.8377686156921539, 0.8424693903048475, 0.8449212893553223, 0.842125812093953]
0.8407547805519622
0.009074600238575025


In [ ]:
print(logistic_praucscore)
print(np.mean(logistic_praucscore))
print(np.std(logistic_praucscore))

[0.9199754154873104, 0.907669203309437, 0.927124557660441, 0.916408703466326, 0.9181584524777382, 0.9169287822305064, 0.9167669947110416, 0.9191354151166524, 0.9203102218994963, 0.9189956017291623]
0.9181473348088112
0.004544345503615452


In [ ]:
print(xgb_f1scores)
print(np.mean(xgb_f1scores))
print(np.std(xgb_f1scores))

[0.8985166779383476, 0.8704453441295547, 0.9029719573013291, 0.9050902844285572, 0.8944155259944733, 0.8659632504116006, 0.8986856200817122, 0.8961311383644305, 0.8912886319416758, 0.8989653476627809]
0.8922473778254462
0.012620343672827718


In [ ]:
print(xgb_rocaucscore)
print(np.mean(xgb_rocaucscore))
print(np.std(xgb_rocaucscore))

[0.8893548487489108, 0.8616332627909872, 0.8976798829826964, 0.8947427797833934, 0.8846671542387651, 0.8551505497251375, 0.8920227386306847, 0.8906015742128935, 0.879294727636182, 0.8949587706146926]
0.8840106289364345
0.013836205980038227


In [ ]:
print(xgb_praucscore)
print(np.mean(xgb_praucscore))
print(np.std(xgb_praucscore))

[0.9427796231400275, 0.9289403881055424, 0.9477362280398263, 0.945250924256342, 0.9403503694440435, 0.9256731048193991, 0.9447705963578831, 0.9443059819454342, 0.9375737725533931, 0.9468560214249869]
0.9404237010086878
0.00717803516450745
