In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [3]:
df_larger_annotated = pd.read_csv('/content/drive/MyDrive/IDSIA Biomedical Texts/Tweets Project/large16k_with_annotated_part_and_feat_incl_emb.csv')
df_larger_annotated

Unnamed: 0            status_id              user_id  \
0             118  1245863648913813504  1148511375976611840   
1             308  1245863885204152321             20817049   
2             327  1245863937247076353            866442835   
3             482  1245864250700001280   919734991390724096   
4             594  1245864498344296449   895000278201708545   
...           ...                  ...                  ...   
16535     3246439  1248759142933835776            162719860   
16536     3246515  1248759404666765312            381842403   
16537     3247045  1248761313091780609           1621100112   
16538     3247300  1248762191660093451            494002295   
16539     3247370  1248762451539222528           2501039616   

                 created_at  \
0      2020-04-03T00:00:15Z   
1      2020-04-03T00:01:11Z   
2      2020-04-03T00:01:24Z   
3      2020-04-03T00:02:39Z   
4      2020-04-03T00:03:38Z   
...                     ...   
16535  2020-04-10T23:45:55Z   
16536  2020-04-10T23:46:57Z   
16537  2020-04-10T23:54:32Z   
16538  2020-04-10T23:58:02Z   
16539  2020-04-10T23:59:03Z   

                                                    text  panic_kw_count  \
0      Dear World👨‍👩‍👧‍👦, you need not panic, because...               1   
1      .@fordnation says releasing the projection mod...               1   
2      "Neurologists around the world say that a smal...               0   
3      Coronavirus: More than one million cases confi...               0   
4      This is my Gov, @henrymcmaster, today, 4/2/202...               0   
...                                                  ...             ...   
16535  My story about #specialneeds kids &amp; #silve...               0   
16536  Just a quick update: Thursday afternoon, mum h...               0   
16537  #COVID_19 \n•We are all we've got.\n•Don’t giv...               1   
16538  COVID-19 Mental Health Resources from the Coun...               1   
16539  Dear fellow Bostonians, Massachusetts just rec...               0   

       symptoms_ext_count     i  illness  mental  ...  emo_neg  \
0                       0  0.00    12.50    0.00  ...     6.25   
1                       0  0.00     0.00    0.00  ...     3.57   
2                       1  0.00     5.88    0.00  ...     0.00   
3                       0  2.94     5.88    2.94  ...     2.94   
4                       1  2.38     0.00    0.00  ...     0.00   
...                   ...   ...      ...     ...  ...      ...   
16535                   0  3.70    11.11    7.41  ...     3.70   
16536                   0  2.00     8.00    2.00  ...     2.00   
16537                   0  0.00     0.00    0.00  ...     4.55   
16538                   0  0.00     6.25   12.50  ...     6.25   
16539                   1  0.00     0.00    0.00  ...     0.00   

                                  twitter4sse_embeddings used_for_annotation  \
0      [-0.040745142847299576, 0.011479376815259457, ...                   0   
1      [-0.2589869797229767, 0.14035490155220032, 0.0...                   0   
2      [-0.02708950825035572, 0.20832084119319916, -0...                   0   
3      [-0.23723432421684265, 0.072296142578125, -0.2...                   0   
4      [-0.42780137062072754, 0.127772256731987, -0.2...                   0   
...                                                  ...                 ...   
16535  [-0.2954484224319458, -0.21568302810192108, 0....                   0   
16536  [-0.03530991077423096, 0.17665432393550873, -0...                   0   
16537  [-0.20700444281101227, 0.01790219359099865, 0....                   0   
16538  [-0.2529967129230499, 0.08556650578975677, -0....                   0   
16539  [-0.2330004721879959, 0.15653513371944427, 0.0...                   0   

        A1   A2   A3   A4   A5   A6 majority_vote  
0      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
1      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
2      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
3 

In [4]:
df_larger_annotated[df_larger_annotated['used_for_annotation'] == 1]

Unnamed: 0            status_id              user_id  \
105         21195  1245916048517292033            297944588   
107         21587  1245916935998464005  1116031804165767169   
138         26533  1245928581353467910           3284687677   
172         30413  1245940255993155584  1136453384054034432   
288         50758  1245998640499322881           2677225992   
...           ...                  ...                  ...   
15957     3115183  1248497721775779840             74114924   
16087     3144693  1248575471241093120            143915733   
16305     3197594  1248656868941103104  1224352945833160706   
16441     3230828  1248716546656145413             20393302   
16511     3242099  1248745538079490048             25588808   

                 created_at  \
105    2020-04-03T03:28:28Z   
107    2020-04-03T03:32:00Z   
138    2020-04-03T04:18:16Z   
172    2020-04-03T05:04:40Z   
288    2020-04-03T08:56:40Z   
...                     ...   
15957  2020-04-10T06:27:07Z   
16087  2020-04-10T11:36:04Z   
16305  2020-04-10T16:59:31Z   
16441  2020-04-10T20:56:39Z   
16511  2020-04-10T22:51:51Z   

                                                    text  panic_kw_count  \
105    Fuck you china. I was 2 years clear of severe ...               1   
107    Feeling so off today and I can’t tell if this ...               1   
138    Good lord people we need to stop having people...               1   
172    I'm telling yall, Chill the fuck out!! This Vi...               0   
288    Episode of #CoronaVirus panic. Man took his gl...               1   
...                                                  ...             ...   
15957  Since my anxiety around #coronavirus subsided,...               1   
16087  Irresponsible reporting and telling people sha...               1   
16305  Personally, I don't have a problem with #StayA...               0   
16441  Have reverted back to having panic attacks dur...               1   
16511  haven’t tweeted in 6 months &amp; my thing to ...               1   

       symptoms_ext_count      i  illness  mental  ...  emo_neg  \
105                     0  11.54     3.85    7.69  ...    11.54   
107                     0  12.00     4.00    8.00  ...     8.00   
138                     0   9.52     2.38    4.76  ...     4.76   
172                     1   2.33     4.65    2.33  ...     2.33   
288                     1   6.90     1.72    0.00  ...     1.72   
...                   ...    ...      ...     ...  ...      ...   
15957                   0   6.25     3.13    6.25  ...     9.38   
16087                   1   0.00     5.13    0.00  ...     2.56   
16305                   1   9.09     4.55    9.09  ...     4.55   
16441                   0   7.14     4.76    4.76  ...     7.14   
16511                   0   3.03     3.03    6.06  ...     6.06   

                                  twitter4sse_embeddings used_for_annotation  \
105    [-0.22512023150920868, 0.03707732632756233, 0....                   1   
107    [0.010432062670588493, 0.121722012758255, -0.2...                   1   
138    [-0.20182527601718903, 0.24901598691940308, 0....                   1   
172    [0.18443672358989716, 0.22256337106227875, 0.2...                   1   
288    [-0.07753666490316391, -0.44565826654434204, -...                   1   
...                                                  ...                 ...   
15957  [0.10353126376867294, 0.056257978081703186, -0...                   1   
16087  [-0.029525309801101685, 0.2843950092792511, -0...                   1   
16305  [-0.0216364823281765, 0.2057066708803177, -0.0...                   1   
16441  [-0.1236368715763092, 0.0016770627116784453, -...                   1   
16511  [0.016024738550186157, 0.08114571869373322, 0....                   1   

         A1    A2    A3    A4    A5  A6 majority_vote  
105      PP    PP    PP    PP    PP  PP            PP  
107      PP    PP    PP    PP    PP  PP            PP  
138      PP    UN    PP  PONP 

In [5]:
df_larger_annotated.columns

Index(['Unnamed: 0', 'status_id', 'user_id', 'created_at', 'text',
       'panic_kw_count', 'symptoms_ext_count', 'i', 'illness', 'mental',
       'tone_neg', 'emo_neg', 'twitter4sse_embeddings', 'used_for_annotation',
       'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'majority_vote'],
      dtype='object')

In [6]:
df_larger_annotated['majority_vote'].value_counts()

PP            94
PONP          59
NoMajority    53
UN             7
Name: majority_vote, dtype: int64

## Converting embedding column which is in string to list

In [7]:
df_larger_annotated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16540 entries, 0 to 16539
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Unnamed: 0              16540 non-null  int64  
 1   status_id               16540 non-null  int64  
 2   user_id                 16540 non-null  int64  
 3   created_at              16540 non-null  object 
 4   text                    16540 non-null  object 
 5   panic_kw_count          16540 non-null  int64  
 6   symptoms_ext_count      16540 non-null  int64  
 7   i                       16540 non-null  float64
 8   illness                 16540 non-null  float64
 9   mental                  16540 non-null  float64
 10  tone_neg                16540 non-null  float64
 11  emo_neg                 16540 non-null  float64
 12  twitter4sse_embeddings  16540 non-null  object 
 13  used_for_annotation     16540 non-null  int64  
 14  A1                      213 non-null  

In [8]:
df_larger_annotated['twitter4sse_embeddings'] = df_larger_annotated['twitter4sse_embeddings'].apply(lambda x: eval(x))

In [9]:
type(df_larger_annotated['twitter4sse_embeddings'][0])

list

In [10]:
df_annotated = df_larger_annotated[(df_larger_annotated.used_for_annotation==1) & (df_larger_annotated.majority_vote!="NoMajority")]
df_annotated

Unnamed: 0            status_id              user_id  \
105         21195  1245916048517292033            297944588   
107         21587  1245916935998464005  1116031804165767169   
138         26533  1245928581353467910           3284687677   
172         30413  1245940255993155584  1136453384054034432   
288         50758  1245998640499322881           2677225992   
...           ...                  ...                  ...   
15601     3028959  1250474359715594240   747257810010931201   
15832     3086951  1250568412746612737            256188572   
15838     3088475  1250572544215642112  1172938416125808640   
16087     3144693  1248575471241093120            143915733   
16441     3230828  1248716546656145413             20393302   

                 created_at  \
105    2020-04-03T03:28:28Z   
107    2020-04-03T03:32:00Z   
138    2020-04-03T04:18:16Z   
172    2020-04-03T05:04:40Z   
288    2020-04-03T08:56:40Z   
...                     ...   
15601  2020-04-15T17:21:34Z   
15832  2020-04-15T23:35:18Z   
15838  2020-04-15T23:51:43Z   
16087  2020-04-10T11:36:04Z   
16441  2020-04-10T20:56:39Z   

                                                    text  panic_kw_count  \
105    Fuck you china. I was 2 years clear of severe ...               1   
107    Feeling so off today and I can’t tell if this ...               1   
138    Good lord people we need to stop having people...               1   
172    I'm telling yall, Chill the fuck out!! This Vi...               0   
288    Episode of #CoronaVirus panic. Man took his gl...               1   
...                                                  ...             ...   
15601  I have true compassion for these families, but...               1   
15832  My mom called asked me to come over, she is on...               1   
15838  Having a panic attack while grocery shopping i...               1   
16087  Irresponsible reporting and telling people sha...               1   
16441  Have reverted back to having panic attacks dur...               1   

       symptoms_ext_count      i  illness  mental  ...  emo_neg  \
105                     0  11.54     3.85    7.69  ...    11.54   
107                     0  12.00     4.00    8.00  ...     8.00   
138                     0   9.52     2.38    4.76  ...     4.76   
172                     1   2.33     4.65    2.33  ...     2.33   
288                     1   6.90     1.72    0.00  ...     1.72   
...                   ...    ...      ...     ...  ...      ...   
15601                   0   2.33     2.33    4.65  ...     6.98   
15832                   1  11.11     0.00    3.70  ...     7.41   
15838                   0   9.09     2.27    4.55  ...     6.82   
16087                   1   0.00     5.13    0.00  ...     2.56   
16441                   0   7.14     4.76    4.76  ...     7.14   

                                  twitter4sse_embeddings used_for_annotation  \
105    [-0.22512023150920868, 0.03707732632756233, 0....                   1   
107    [0.010432062670588493, 0.121722012758255, -0.2...                   1   
138    [-0.20182527601718903, 0.24901598691940308, 0....                   1   
172    [0.18443672358989716, 0.22256337106227875, 0.2...                   1   
288    [-0.07753666490316391, -0.44565826654434204, -...                   1   
...                                                  ...                 ...   
15601  [-0.36669501662254333, 0.15450149774551392, -0...                   1   
15832  [-0.0625092014670372, -0.19092148542404175, 0....                   1   
15838  [-0.05952261760830879, -0.3383149802684784, -0...                   1   
16087  [-0.029525309801101685, 0.2843950092792511, -0...                   1   
16441  [-0.1236368715763092, 0.0016770627116784453, -...                   1   

         A1    A2    A3    A4    A5  A6 majority_vote  
105      PP    PP    PP    PP    PP  PP            PP  
107      PP    PP    PP    PP    PP  PP            PP  
138      PP    UN    PP  PONP 

### Label Encoding "Majority Vote" column

In [11]:
from sklearn.preprocessing import LabelEncoder
label_mapping = {"PP": 0, "PONP": 1, "UN": 2}
le = LabelEncoder()
le.fit_transform(list(label_mapping.values()))
df_annotated['label'] = df_annotated['majority_vote'].map(label_mapping)

<ipython-input-11-f820b59bb32b>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_annotated['label'] = df_annotated['majority_vote'].map(label_mapping)


In [12]:
for label, encoded_value in label_mapping.items():
    print(f"Label: {label} - Encoded value: {encoded_value}")

Label: PP - Encoded value: 0
Label: PONP - Encoded value: 1
Label: UN - Encoded value: 2


In [13]:
df_annotated.head()

Unnamed: 0            status_id              user_id  \
105       21195  1245916048517292033            297944588   
107       21587  1245916935998464005  1116031804165767169   
138       26533  1245928581353467910           3284687677   
172       30413  1245940255993155584  1136453384054034432   
288       50758  1245998640499322881           2677225992   

               created_at                                               text  \
105  2020-04-03T03:28:28Z  Fuck you china. I was 2 years clear of severe ...   
107  2020-04-03T03:32:00Z  Feeling so off today and I can’t tell if this ...   
138  2020-04-03T04:18:16Z  Good lord people we need to stop having people...   
172  2020-04-03T05:04:40Z  I'm telling yall, Chill the fuck out!! This Vi...   
288  2020-04-03T08:56:40Z  Episode of #CoronaVirus panic. Man took his gl...   

     panic_kw_count  symptoms_ext_count      i  illness  mental  ...  \
105               1                   0  11.54     3.85    7.69  ...   
107               1                   0  12.00     4.00    8.00  ...   
138               1                   0   9.52     2.38    4.76  ...   
172               0                   1   2.33     4.65    2.33  ...   
288               1                   1   6.90     1.72    0.00  ...   

                                twitter4sse_embeddings  used_for_annotation  \
105  [-0.22512023150920868, 0.03707732632756233, 0....                    1   
107  [0.010432062670588493, 0.121722012758255, -0.2...                    1   
138  [-0.20182527601718903, 0.24901598691940308, 0....                    1   
172  [0.18443672358989716, 0.22256337106227875, 0.2...                    1   
288  [-0.07753666490316391, -0.44565826654434204, -...                    1   

       A1    A2    A3    A4    A5  A6 majority_vote label  
105    PP    PP    PP    PP    PP  PP            PP     0  
107    PP    PP    PP    PP    PP  PP            PP     0  
138    PP    UN    PP  PONP    PP  PP            PP     0  
172  PONP  PONP  PONP  PONP  PONP  PP          PONP     1  
288    PP    PP    PP    PP    PP  PP            PP     0  

[5 rows x 22 columns]

### Standardization of LIWC features



In [14]:
df_annotated.columns

Index(['Unnamed: 0', 'status_id', 'user_id', 'created_at', 'text',
       'panic_kw_count', 'symptoms_ext_count', 'i', 'illness', 'mental',
       'tone_neg', 'emo_neg', 'twitter4sse_embeddings', 'used_for_annotation',
       'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'majority_vote', 'label'],
      dtype='object')

In [15]:
df_annotated[['i','illness', 'mental', 'tone_neg', 'emo_neg']]

i  illness  mental  tone_neg  emo_neg
105    11.54     3.85    7.69     26.92    11.54
107    12.00     4.00    8.00      8.00     8.00
138     9.52     2.38    4.76      7.14     4.76
172     2.33     4.65    2.33      6.98     2.33
288     6.90     1.72    0.00      3.45     1.72
...      ...      ...     ...       ...      ...
15601   2.33     2.33    4.65     13.95     6.98
15832  11.11     0.00    3.70      7.41     7.41
15838   9.09     2.27    4.55      9.09     6.82
16087   0.00     5.13    0.00      5.13     2.56
16441   7.14     4.76    4.76      7.14     7.14

[160 rows x 5 columns]

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [17]:
standardized_liwc = sc.fit_transform(df_annotated[['i','illness', 'mental', 'tone_neg', 'emo_neg']])

In [18]:
standardized_liwc

array([[ 1.04879875e+00, -7.72953559e-02,  7.78759369e-01,
         2.89145158e+00,  5.86838072e-01],
       [ 1.14686465e+00, -2.41104780e-02,  8.65488301e-01,
        -2.99290140e-01, -3.60841791e-02],
       [ 6.18161564e-01, -5.98507160e-01, -4.09689292e-02,
        -4.44323854e-01, -6.06216409e-01],
       [-9.14651004e-01,  2.06357326e-01, -7.20811852e-01,
        -4.71306871e-01, -1.03381558e+00],
       [ 5.96123386e-02, -8.32520623e-01, -1.37267770e+00,
        -1.06661968e+00, -1.14115529e+00],
       [-9.48760881e-01, -6.72965989e-01, -7.65575172e-01,
        -5.48883044e-01, -6.78362771e-01],
       [-1.41137608e+00, -5.09865697e-01, -1.37267770e+00,
         5.70912147e-01,  4.09111667e-01],
       [ 2.28029853e-01, -7.72953559e-02, -2.95560312e-01,
        -9.99162134e-01, -7.66346140e-01],
       [-6.50299463e-01, -1.44237389e+00, -3.73896122e-01,
         1.57734705e-01,  4.40785680e-01],
       [ 2.70667198e-01, -5.09865697e-01,  9.89164459e-02,
        -7.61374300e-01

In [19]:
df_annotated['label'].value_counts()

0    94
1    59
2     7
Name: label, dtype: int64

### XGB

In [20]:
# from sklearn.model_selection import StratifiedKFold
# folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import xgboost as xgb
from sklearn.metrics import roc_auc_score, make_scorer # not able to import balanced_accuray_score
from sklearn.model_selection import GridSearchCV # cross validation, used for hyperparamter tuning
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import f1_score, classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve, auc
import seaborn as sns

In [22]:
X = np.array(df_annotated['twitter4sse_embeddings'].tolist())    # run this for only embeddings

#X = np.concatenate((    standardized_liwc, np.array(df_annotated['twitter4sse_embeddings'].tolist())   ), axis=1)    # run this for emb + only liwc

#emb_liwc = np.concatenate((    standardized_liwc, np.array(df_annotated['twitter4sse_embeddings'].tolist())   ), axis=1)   # run these 2 for emb + liwc + 2 features
#X = np.concatenate(  (df_annotated[['panic_kw_count', 'symptoms_ext_count']].values, emb_liwc    ), axis=1)

#X = standardized_liwc  # run this for onlt liwc

#X = np.concatenate((   standardized_liwc, df_annotated[['panic_kw_count', 'symptoms_ext_count']].values   ), axis=1)   # run this for liwc + 2 features

y = np.array(df_annotated['label'])

In [23]:
X

array([[-2.25120232e-01,  3.70773263e-02,  3.17902528e-02, ...,
        -4.30038571e-02,  1.49781048e-01, -5.37211038e-02],
       [ 1.04320627e-02,  1.21722013e-01, -2.69894660e-01, ...,
         2.98047848e-02,  3.91920984e-01,  4.32758518e-02],
       [-2.01825276e-01,  2.49015987e-01,  5.97718619e-02, ...,
         2.95174539e-01,  2.75589973e-01,  2.05261290e-01],
       ...,
       [-5.95226176e-02, -3.38314980e-01, -8.80411789e-02, ...,
        -1.57644153e-01,  5.35904020e-02, -4.30524647e-02],
       [-2.95253098e-02,  2.84395009e-01, -1.44363359e-01, ...,
         4.79702749e-06,  3.48803520e-01, -2.18136534e-01],
       [-1.23636872e-01,  1.67706271e-03, -1.11626983e-01, ...,
        -2.22300664e-01,  2.22533271e-01,  1.02165766e-01]])

In [24]:
X.shape

(160, 768)

In [25]:
# Ref - https://towardsdatascience.com/micro-macro-weighted-averages-of-f1-score-clearly-explained-b603420b292f
xgb_f1scores = []
xgb_micro_f1scores = []
xgb_macro_f1scores = []
xgb_rocaucscore = []
xgb_praucscore = []

for run in range(10):

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=run, stratify = y)

    clf_xgb = xgb.XGBClassifier(objective='multi:softmax', missing=0, seed=42, num_class=3)

    # XGBoost
    clf_xgb.fit(X_train, y_train,
              verbose=False,  # set to True for individual use
              early_stopping_rounds=10,
              #eval_metrics='aucpr',
              eval_set = [(X_test,y_test)])
    y_pred = clf_xgb.predict(X_test)

    f1 = f1_score(y_test, y_pred,average='weighted')
    xgb_f1scores.append(f1)

    micro_f1 = f1_score(y_test, y_pred, average='micro')
    xgb_micro_f1scores.append(micro_f1)

    macro_f1 = f1_score(y_test, y_pred, average='macro')
    xgb_macro_f1scores.append(macro_f1)

    # class_report = classification_report(y_test, y_pred)   # this will print reports of all 10 different sets of folds
    # print(class_report)

    # cm = confusion_matrix(y_test, y_pred)    # this will print CMs of all 10 different sets of folds
    # plt.figure(figsize=(8, 6))
    # labels = ['PO', 'PONP', 'UN']
    # sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
    # plt.xlabel('Predicted')
    # plt.ylabel('True')
    # plt.title('TrainTest 10 iter liwc + 2features')
    # plt.show()

    #rocaucscore = roc_auc_score(y_test, y_pred, multi_class='ovr')
    #xgb_rocaucscore.append(rocaucscore)

    # print(y_test.shape, y_pred.shape)
    # y_pred_prob = clf_xgb.predict_proba(X_test)
    # print(np.unique(y_test))
    # print(y_pred_prob.shape[1])
    # rocaucscore = roc_auc_score(y_test, y_pred_prob, multi_class='ovo')

    # precision, recall, thresholds = precision_recall_curve(y_test, y_pred)  # Compute precision, recall, and thresholds
    # pr_auc = auc(recall, precision)  # Calculate PR-AUC
    # xgb_praucscore.append(pr_auc)

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`se

In [26]:
print(xgb_f1scores)
print(np.mean(xgb_f1scores))
print(np.std(xgb_f1scores))

[0.8087085678549094, 0.8574561403508772, 0.8338983050847458, 0.8553268765133172, 0.7590561648388169, 0.7586669734621875, 0.8379953379953379, 0.8553268765133172, 0.7926957223567394, 0.8146551724137931]
0.8173786137384041
0.035671691382249356


In [27]:
print(xgb_micro_f1scores)
print(np.mean(xgb_micro_f1scores))
print(np.std(xgb_micro_f1scores))

[0.8125, 0.875, 0.8541666666666666, 0.875, 0.7708333333333333, 0.7708333333333333, 0.8541666666666666, 0.875, 0.8125, 0.8333333333333334]
0.8333333333333334
0.03841476857205372


In [28]:
print(xgb_macro_f1scores)
print(np.mean(xgb_macro_f1scores))
print(np.std(xgb_macro_f1scores))

[0.5550343964978112, 0.5902255639097745, 0.5717514124293785, 0.5907990314769975, 0.5177799933532735, 0.520631998772818, 0.5765345765345765, 0.5907990314769975, 0.5414043583535109, 0.558109833971903]
0.5613070196777041
0.02628982050197851


In [ ]:
# print(xgb_rocaucscore)
# print(np.mean(xgb_rocaucscore))
# print(np.std(xgb_rocaucscore))

In [ ]:
# print(xgb_praucscore)
# print(np.mean(xgb_praucscore))
# print(np.std(xgb_praucscore))

In [ ]:
# proof that the model does predict 2 (UN) label also
for i in range(10):
  print(clf_xgb.predict([df_larger_annotated['twitter4sse_embeddings'][i]]))
  print(clf_xgb.predict_proba([df_larger_annotated['twitter4sse_embeddings'][i]]))

[1]
[[0.03293658 0.9507418  0.0163216 ]]
[1]
[[0.09048565 0.85437334 0.05514105]]
[1]
[[0.15439577 0.78083724 0.06476697]]
[0]
[[0.8707819  0.10830905 0.02090903]]
[1]
[[0.08320665 0.88745123 0.02934218]]
[1]
[[0.04822434 0.9364322  0.01534356]]
[1]
[[0.04184744 0.92790407 0.03024845]]
[1]
[[0.17824298 0.7616287  0.06012838]]
[1]
[[0.09151273 0.8518731  0.05661417]]
[0]
[[0.9088463  0.0583183  0.03283539]]


### Ignore

In [ ]:
X = np.array(df_annotated['twitter4sse_embeddings'].to_list())
y = np.array(df_annotated['label'])

In [ ]:
X

array([[-2.25120232e-01,  3.70773263e-02,  3.17902528e-02, ...,
        -4.30038571e-02,  1.49781048e-01, -5.37211038e-02],
       [ 1.04320627e-02,  1.21722013e-01, -2.69894660e-01, ...,
         2.98047848e-02,  3.91920984e-01,  4.32758518e-02],
       [-2.01825276e-01,  2.49015987e-01,  5.97718619e-02, ...,
         2.95174539e-01,  2.75589973e-01,  2.05261290e-01],
       ...,
       [-5.95226176e-02, -3.38314980e-01, -8.80411789e-02, ...,
        -1.57644153e-01,  5.35904020e-02, -4.30524647e-02],
       [-2.95253098e-02,  2.84395009e-01, -1.44363359e-01, ...,
         4.79702749e-06,  3.48803520e-01, -2.18136534e-01],
       [-1.23636872e-01,  1.67706271e-03, -1.11626983e-01, ...,
        -2.22300664e-01,  2.22533271e-01,  1.02165766e-01]])

In [ ]:
len(X), len(X[0])

(160, 768)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None, stratify = y)

In [ ]:
# # Converting all to 2D
# X_train = X_train.values.reshape(-1,1)
# y_train = y_train.values.reshape(-1,1)
# X_test = X_test.values.reshape(-1,1)
# y_test = y_test.values.reshape(-1,1)

In [ ]:
clf_xgbtrial = xgb.XGBClassifier(objective='binary:logistic', missing=0, seed=42)

In [ ]:
clf_xgbtrial = xgb.XGBClassifier(objective='multi:softmax', missing=0, seed=42, num_class=3)

In [ ]:
clf_xgbtrial = xgb.XGBClassifier(objective='multi:softprob', missing=0, seed=42, num_class=3)

In [ ]:
clf_xgbtrial.fit(X_train, y_train,
              verbose=False,  # set to True for individual use
              early_stopping_rounds=10,
              #eval_metrics='aucpr',
              eval_set = [(X_test,y_test)])

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=0, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_class=3,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [ ]:
clf_xgbtrial.predict([np.array(df_larger_annotated['twitter4sse_embeddings'][0])])

array([1])

In [ ]:
for i in range(10):
  print(clf_xgbtrial.predict([df_larger_annotated['twitter4sse_embeddings'][i]]))
  print(clf_xgbtrial.predict_proba([df_larger_annotated['twitter4sse_embeddings'][i]]))

[1]
[[0.04106402 0.9217991  0.03713684]]
[0]
[[0.5084511  0.34997576 0.14157312]]
[2]
[[0.09202711 0.38705197 0.5209209 ]]
[0]
[[0.86973083 0.06710157 0.06316756]]
[0]
[[0.68987304 0.22916467 0.08096224]]
[1]
[[0.10174033 0.667774   0.23048568]]
[1]
[[0.04896858 0.8381388  0.11289257]]
[0]
[[0.6560702  0.22121851 0.12271132]]
[2]
[[0.10455995 0.38553032 0.50990975]]
[0]
[[0.83318996 0.08592378 0.08088627]]


In [ ]:
import numpy as np
import xgboost as xgb

# Example data
X = np.random.randn(10, 5)  # 10 samples, 5 features
y = np.random.randint(0, 3, 10)  # 3 classes

# Create the XGBoost DMatrix
dtrain = xgb.DMatrix(X, label=y)

# Set the XGBoost parameters
params = {
    'objective': 'multi:softmax',
    'num_class': 3
}

# Train the XGBoost model
model_softmax = xgb.train(params, dtrain)

# Predict using multi:softmax
y_pred_softmax = model_softmax.predict(dtrain)

# Set the XGBoost parameters for multi:softprob
params['objective'] = 'multi:softprob'

# Train the XGBoost model with multi:softprob
model_softprob = xgb.train(params, dtrain)

# Predict using multi:softprob
y_pred_softprob = model_softprob.predict(dtrain)

# Print the outputs
print("Predictions using multi:softmax:")
print(y_pred_softmax)
print("Predictions using multi:softprob:")
print(y_pred_softprob)


Predictions using multi:softmax:
[0. 1. 0. 1. 0. 2. 2. 2. 0. 2.]
Predictions using multi:softprob:
[[0.7572623  0.1752327  0.06750501]
 [0.13126607 0.6804327  0.18830131]
 [0.7668154  0.17744331 0.05574123]
 [0.15108883 0.6926127  0.15629849]
 [0.7346571  0.04288264 0.22246026]
 [0.13268174 0.07888183 0.7884364 ]
 [0.16424914 0.10219272 0.7335582 ]
 [0.1628676  0.13529077 0.7018416 ]
 [0.5279136  0.18384962 0.28823683]
 [0.18762141 0.07388511 0.7384935 ]]


### Testing model on Messy dataset and gettiing discrepancies

In [ ]:
df_messy = df_larger_annotated[(df_larger_annotated.used_for_annotation==1) & (df_larger_annotated.majority_vote=="NoMajority")]
df_messy.head()

Unnamed: 0            status_id              user_id  \
381        70068  1246056304919097354            361755825   
538       100700  1246091601618837505            427329617   
920       186038  1246189954163761153   917105229467979776   
1137      238381  1249997318109134848             21745651   
2358      504781  1246487955583238145  1058524126724317184   

                created_at                                               text  \
381   2020-04-03T12:45:48Z  NEWS! Conquer Anxiety, Stress and Panic Attack...   
538   2020-04-03T15:06:03Z  As someone who has experienced anxiety and pan...   
920   2020-04-03T21:36:52Z  When you are having a panic attack and one of ...   
1137  2020-04-14T09:45:59Z  Heard countries have done/are considering exte...   
2358  2020-04-04T17:21:01Z  Panic buying, #supplychain shake-ups and compa...   

      panic_kw_count  symptoms_ext_count     i  illness  mental  ...  emo_neg  \
381                1                   0  2.63     2.63    7.89  ...    21.05   
538                1                   0  5.88     5.88    5.88  ...    17.65   
920                1                   1  0.00     3.85    7.69  ...    19.23   
1137               1                   0  2.22     2.22    4.44  ...     2.22   
2358               1                   1  0.00     3.85    0.00  ...     3.85   

                                 twitter4sse_embeddings used_for_annotation  \
381   [-0.25782403349876404, 0.08037050813436508, 0....                   1   
538   [-0.5726941823959351, 0.12105824798345566, 0.1...                   1   
920   [-0.06552565842866898, 0.018419360741972923, -...                   1   
1137  [-0.18501493334770203, 0.13860271871089935, 0....                   1   
2358  [-0.13047395646572113, -0.052925579249858856, ...                   1   

      A1    A2    A3    A4    A5    A6 majority_vote  
381   UN  PONP    UN  PONP    UN  PONP    NoMajority  
538   PP  PONP    PP  PONP  PONP    PP    NoMajority  
920   PP    PP    PP  PONP  PONP  PONP    NoMajority  
1137  PP  PONP     ?    PP     ?     ?    NoMajority  
2358  UN    UN  PONP  PONP  PONP    UN    NoMajority  

[5 rows x 21 columns]

In [ ]:
messy_standardized_liwc = sc.fit_transform(df_messy[['i','illness', 'mental', 'tone_neg', 'emo_neg']])
messy_standardized_liwc

array([[-9.45642250e-01, -4.00896041e-01,  7.18344950e-01,
         1.53264625e+00,  2.31700985e+00],
       [-2.03222571e-01,  6.00036603e-01,  1.82340975e-01,
         1.04213412e+00,  1.69701196e+00],
       [-1.54643110e+00, -2.51613257e-02,  6.65011221e-01,
         1.27007799e+00,  1.98512863e+00],
       [-1.03930135e+00, -5.27167544e-01, -2.01661873e-01,
        -1.18392534e+00, -1.11668431e+00],
       [-1.54643110e+00, -2.51613257e-02, -1.38567065e+00,
        -3.94777881e-01, -8.19450032e-01],
       [ 3.68934091e+00, -5.70284643e-01, -2.73662407e-01,
         2.99152514e-01,  7.57897523e-01],
       [-9.89045246e-01,  2.92057328e-01, -8.43276694e-02,
        -4.48157142e-01, -1.86687487e-01],
       [-1.54643110e+00, -1.21088154e+00,  6.65011221e-01,
        -3.94777881e-01, -1.19217129e-01],
       [-2.42056831e-01,  5.47680126e-01,  1.37007305e-01,
         5.57392723e-01,  5.62780543e-01],
       [ 4.40969273e-01,  7.97143339e-01, -8.06999696e-01,
        -1.19113875e+00

In [ ]:
# df_messy_prob_label = pd.DataFrame(index=df_messy.index)   # empty dataframe with index those of messy dataframe

In [ ]:
df_messy_prob_label = df_messy[['text']]
df_messy_prob_label

text
381    NEWS! Conquer Anxiety, Stress and Panic Attack...
538    As someone who has experienced anxiety and pan...
920    When you are having a panic attack and one of ...
1137   Heard countries have done/are considering exte...
2358   Panic buying, #supplychain shake-ups and compa...
2540   Me: Yay! #Saturday!\n\nMy #Anxiety: Hi!\n\nMe:...
2859   I wish Boris all the best. Will the media rele...
3306   We are all gonna have HELLA trust issues when ...
3403   My son  19 year old son in Suffolk county NY j...
3763   Has this #coronavirus made us all paranoid? I'...
3886   My wife was speaking to me and, after 30s of c...
4276   I think I relate to this because coping with a...
4777   Why did I start watching #pandemic? I feel stu...
5451   "I’d be lying if I said that this pandemic did...
6240   watching the perks of being a wallflower over ...
6372   I miss the days when I used to be able to scro...
6587   Three weeks into quarantine and chill, and dam...
7326   FYI\nFear of going out of home = Agoraphobia\n...
7453   Reason fifty million why it's difficult to be ...
7818   Is this #coronavirus-induced shortness of brea...
8069   Society right now is my antisocial dreams. Peo...
8083   I know this has been a rough couple of weeks a...
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...
8408   I was confident on day one we would beat it \n...
8632   As someone who has experienced anxiety and pan...
8746   The Faint - Paranoiattack https://t.co/glhSnMN...
8967   One time I was scared and went to the hospital...
9120   you know quarantine’s got you depressed af whe...
9122   I think I'm going to only focus on local news ...
9183   Tbh, the daily updates of #Covid19 had given m...
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...
9729   Breaking your addiction to #BreakingNews - "It...
10358  BBC News - Coronavirus and anxiety: 'Following...
10651  I dont know if this is PTSD... but anytime i s...
10790  I'm ridiculously chill in emergency situations...
11390  Emergency Alert — state of Illinois vs. state ...
11489  #Coronavirus and anxiety: 'Following the news ...
11563  Anyone else find themselves having little pani...
11810  I've just discovered this if you are a #vulner...
12257  Hi Everyone-\n\nI, like many, have been suffer...
12663  Thank you to @danjlevy and the amazing cast of...
12715  I've seen all the charts about the symptoms of...
12861  Its 2am. I am having a bad night. Many are hav...
13920  Just going to @Target &amp; grocery shopping i...
13991  Enough pointless autistic meltdowns. I'm gonna...
14670  Things I developed for the first time during t...
15070  Donald Trump, the passive-aggressive Sadist So...
15100  Reporter Jim @Acosta reads Trump's own words b...
15161  One thing people should know: I'm 85, I don’t ...
15613  Panic attacks, diarrhea, obsessive list making...
15957  Since my anxiety around #coronavirus subsided,...
16305  Personally, I don't have a problem with #StayA...
16511  haven’t tweeted in 6 months &amp; my thing to ...

In [ ]:
# run for only emb
# a = df_messy['twitter4sse_embeddings'].apply(lambda x: clf_xgb.predict_proba([x]))
# a = pd.DataFrame(a)
# a

# run for emb+liwc
# a = clf_xgb.predict_proba(   np.concatenate((    messy_standardized_liwc, np.array(df_messy['twitter4sse_embeddings'].tolist())   ), axis=1)        )
# a = pd.DataFrame(a, columns=['PP', 'PONP', 'UN'])
# a

# run these 2 for emb + liwc + 2 features
# messy_emb_liwc = np.concatenate((    messy_standardized_liwc, np.array(df_messy['twitter4sse_embeddings'].tolist())   ), axis=1)
# X = np.concatenate(  (df_messy[['panic_kw_count', 'symptoms_ext_count']].values, messy_emb_liwc    ), axis=1)
# a = clf_xgb.predict_proba(X)
# a = pd.DataFrame(a, columns=['PP', 'PONP', 'UN'])
# a

# run this for only liwc
# a = clf_xgb.predict_proba(messy_standardized_liwc)
# a = pd.DataFrame(a, columns=['PP', 'PONP', 'UN'])
# a

# run this for liwc+2features
X = np.concatenate((   messy_standardized_liwc, df_messy[['panic_kw_count', 'symptoms_ext_count']].values   ), axis=1)
a = clf_xgb.predict_proba(X)
a = pd.DataFrame(a, columns=['PP', 'PONP', 'UN'])
a

PP      PONP        UN
0   0.683731  0.207900  0.108368
1   0.678802  0.179644  0.141554
2   0.683731  0.207900  0.108368
3   0.093473  0.818201  0.088326
4   0.093473  0.818201  0.088326
5   0.804405  0.098934  0.096661
6   0.093473  0.818201  0.088326
7   0.757678  0.138887  0.103435
8   0.620373  0.212323  0.167305
9   0.807783  0.086507  0.105710
10  0.828118  0.086940  0.084942
11  0.826422  0.087797  0.085780
12  0.637099  0.099410  0.263491
13  0.828118  0.086940  0.084942
14  0.804405  0.098934  0.096661
15  0.645397  0.220015  0.134588
16  0.529368  0.313118  0.157513
17  0.683731  0.207900  0.108368
18  0.825272  0.088379  0.086349
19  0.683731  0.207900  0.108368
20  0.807783  0.086507  0.105710
21  0.825272  0.088379  0.086349
22  0.807783  0.086507  0.105710
23  0.807783  0.086507  0.105710
24  0.703240  0.175296  0.121464
25  0.711695  0.129751  0.158554
26  0.828118  0.086940  0.084942
27  0.093884  0.512969  0.393147
28  0.828118  0.086940  0.084942
29  0.093473  0.818201  0.088326
30  0.093473  0.818201  0.088326
31  0.097188  0.814848  0.087964
32  0.534834  0.148253  0.316913
33  0.677529  0.082097  0.240374
34  0.683731  0.207900  0.108368
35  0.093473  0.818201  0.088326
36  0.828118  0.086940  0.084942
37  0.757678  0.138887  0.103435
38  0.113261  0.618841  0.267898
39  0.826422  0.087797  0.085780
40  0.828118  0.086940  0.084942
41  0.797710  0.102320  0.099970
42  0.782806  0.109859  0.107335
43  0.825272  0.088379  0.086349
44  0.804405  0.098934  0.096661
45  0.825272  0.088379  0.086349
46  0.808583  0.096821  0.094596
47  0.508312  0.327127  0.164560
48  0.563660  0.290304  0.146036
49  0.757678  0.138887  0.103435
50  0.669429  0.214947  0.115624
51  0.785819  0.096392  0.117790
52  0.757678  0.138887  0.103435

In [ ]:
# run for only emb
# df_messy_prob_label['PP_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][0])
# df_messy_prob_label['PONP_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][1])
# df_messy_prob_label['UN_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][2])

# run for 1. emb+liwc AND 2. emb+liwc+2features AND 3. only liwc AND 4. LIWC + 2 features
df_messy_prob_label['PP_prob'] = list(a['PP'])
df_messy_prob_label['PONP_prob'] = list(a['PONP'])
df_messy_prob_label['UN_prob'] = list(a['UN'])

<ipython-input-274-4fcee718dbeb>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['PP_prob'] = list(a['PP'])
<ipython-input-274-4fcee718dbeb>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['PONP_prob'] = list(a['PONP'])
<ipython-input-274-4fcee718dbeb>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/p

In [ ]:
df_messy_prob_label

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.683731   0.207900   
538    As someone who has experienced anxiety and pan...  0.678802   0.179644   
920    When you are having a panic attack and one of ...  0.683731   0.207900   
1137   Heard countries have done/are considering exte...  0.093473   0.818201   
2358   Panic buying, #supplychain shake-ups and compa...  0.093473   0.818201   
2540   Me: Yay! #Saturday!\n\nMy #Anxiety: Hi!\n\nMe:...  0.804405   0.098934   
2859   I wish Boris all the best. Will the media rele...  0.093473   0.818201   
3306   We are all gonna have HELLA trust issues when ...  0.757678   0.138887   
3403   My son  19 year old son in Suffolk county NY j...  0.620373   0.212323   
3763   Has this #coronavirus made us all paranoid? I'...  0.807783   0.086507   
3886   My wife was speaking to me and, after 30s of c...  0.828118   0.086940   
4276   I think I relate to this because coping with a...  0.826422   0.087797   
4777   Why did I start watching #pandemic? I feel stu...  0.637099   0.099410   
5451   "I’d be lying if I said that this pandemic did...  0.828118   0.086940   
6240   watching the perks of being a wallflower over ...  0.804405   0.098934   
6372   I miss the days when I used to be able to scro...  0.645397   0.220015   
6587   Three weeks into quarantine and chill, and dam...  0.529368   0.313118   
7326   FYI\nFear of going out of home = Agoraphobia\n...  0.683731   0.207900   
7453   Reason fifty million why it's difficult to be ...  0.825272   0.088379   
7818   Is this #coronavirus-induced shortness of brea...  0.683731   0.207900   
8069   Society right now is my antisocial dreams. Peo...  0.807783   0.086507   
8083   I know this has been a rough couple of weeks a...  0.825272   0.088379   
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...  0.807783   0.086507   
8408   I was confident on day one we would beat it \n...  0.807783   0.086507   
8632   As someone who has experienced anxiety and pan...  0.703240   0.175296   
8746   The Faint - Paranoiattack https://t.co/glhSnMN...  0.711695   0.129751   
8967   One time I was scared and went to the hospital...  0.828118   0.086940   
9120   you know quarantine’s got you depressed af whe...  0.093884   0.512969   
9122   I think I'm going to only focus on local news ...  0.828118   0.086940   
9183   Tbh, the daily updates of #Covid19 had given m...  0.093473   0.818201   
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...  0.093473   0.818201   
9729   Breaking your addiction to #BreakingNews - "It...  0.097188   0.814848   
10358  BBC News - Coronavirus and anxiety: 'Following...  0.534834   0.148253   
10651  I dont know if this is PTSD... but anytime i s...  0.677529   0.082097   
10790  I'm ridiculously chill in emergency situations...  0.683731   0.207900   
11390  Emergency Alert — state of Illinois vs. state ...  0.093473   0.818201   
11489  #Coronavirus and anxiety: 'Following the news ...  0.828118   0.086940   
11563  Anyone else find themselves having little pani...  0.757678   0.138887   
11810  I've just discovered this if you are a #vulner...  0.113261   0.618841   
12257  Hi Everyone-\n\nI, like many, have been suffer...  0.826422   0.087797   
12663  Thank you to @danjlevy and the amazing cast of...  0.828118   0.086940   
12715  I've seen all the charts about the symptoms of...  0.797710   0.102320   
12861  Its 2am. I am having a bad night. Many are hav...  0.782806   0.109859   
13920  Just going to @Target &amp; grocery shopping i...  0.825272   0.088379   
13991  Enough pointless autistic meltdowns. I'm gonna...  0.804405   0.098934   
14670  Things I developed for the first time during t...  0.825272   0.088379   
15070  Donald Trump, the passive-aggressive Sadist So...  0.808583   0.096821   
15100  Reporter Jim @Acosta reads Trump's own words b...  0.508312   0.327127   
15161  One thing people should know: I'm 85, I don’t ...  0.563660   0.290304   
15

In [ ]:
# to add label column
# b = df_messy['twitter4sse_embeddings'].apply(lambda x: clf_xgb.predict([x]))
# b = pd.DataFrame(b)
# b

In [ ]:
# df_messy_prob_label['predicted_label'] = b['twitter4sse_embeddings'].apply(lambda x: x[0])

In [ ]:
# df_messy_prob_label

In [ ]:
# condition where the highest probablity is less than 0.7
condition1 = df_messy_prob_label[['PP_prob', 'PONP_prob', 'UN_prob']].max(axis=1) < 0.7
df_messy_prob_label[condition1]

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.683731   0.207900   
538    As someone who has experienced anxiety and pan...  0.678802   0.179644   
920    When you are having a panic attack and one of ...  0.683731   0.207900   
3403   My son  19 year old son in Suffolk county NY j...  0.620373   0.212323   
4777   Why did I start watching #pandemic? I feel stu...  0.637099   0.099410   
6372   I miss the days when I used to be able to scro...  0.645397   0.220015   
6587   Three weeks into quarantine and chill, and dam...  0.529368   0.313118   
7326   FYI\nFear of going out of home = Agoraphobia\n...  0.683731   0.207900   
7818   Is this #coronavirus-induced shortness of brea...  0.683731   0.207900   
9120   you know quarantine’s got you depressed af whe...  0.093884   0.512969   
10358  BBC News - Coronavirus and anxiety: 'Following...  0.534834   0.148253   
10651  I dont know if this is PTSD... but anytime i s...  0.677529   0.082097   
10790  I'm ridiculously chill in emergency situations...  0.683731   0.207900   
11810  I've just discovered this if you are a #vulner...  0.113261   0.618841   
15100  Reporter Jim @Acosta reads Trump's own words b...  0.508312   0.327127   
15161  One thing people should know: I'm 85, I don’t ...  0.563660   0.290304   
15957  Since my anxiety around #coronavirus subsided,...  0.669429   0.214947   

        UN_prob  
381    0.108368  
538    0.141554  
920    0.108368  
3403   0.167305  
4777   0.263491  
6372   0.134588  
6587   0.157513  
7326   0.108368  
7818   0.108368  
9120   0.393147  
10358  0.316913  
10651  0.240374  
10790  0.108368  
11810  0.267898  
15100  0.164560  
15161  0.146036  
15957  0.115624

In [ ]:
# condition where the difference between 2 highest probabilites in less than 0.4
c = df_messy_prob_label[['PP_prob', 'PONP_prob', 'UN_prob']].apply(lambda x: sorted(x, reverse=True), axis=1)
condition2 = c.apply(lambda x: x[0] - x[1]) < 0.4
df_messy_prob_label[condition2]

text   PP_prob  PONP_prob  \
4777   Why did I start watching #pandemic? I feel stu...  0.637099   0.099410   
6587   Three weeks into quarantine and chill, and dam...  0.529368   0.313118   
9120   you know quarantine’s got you depressed af whe...  0.093884   0.512969   
10358  BBC News - Coronavirus and anxiety: 'Following...  0.534834   0.148253   
11810  I've just discovered this if you are a #vulner...  0.113261   0.618841   
15100  Reporter Jim @Acosta reads Trump's own words b...  0.508312   0.327127   
15161  One thing people should know: I'm 85, I don’t ...  0.563660   0.290304   

        UN_prob  
4777   0.263491  
6587   0.157513  
9120   0.393147  
10358  0.316913  
11810  0.267898  
15100  0.164560  
15161  0.146036

In [ ]:
df_messy_prob_label['cond1'] = np.where(condition1, 1, 0)
df_messy_prob_label['cond2'] = np.where(condition2, 1, 0)

<ipython-input-278-1ced394e49c0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['cond1'] = np.where(condition1, 1, 0)
<ipython-input-278-1ced394e49c0>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['cond2'] = np.where(condition2, 1, 0)


In [ ]:
df_messy_prob_label

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.683731   0.207900   
538    As someone who has experienced anxiety and pan...  0.678802   0.179644   
920    When you are having a panic attack and one of ...  0.683731   0.207900   
1137   Heard countries have done/are considering exte...  0.093473   0.818201   
2358   Panic buying, #supplychain shake-ups and compa...  0.093473   0.818201   
2540   Me: Yay! #Saturday!\n\nMy #Anxiety: Hi!\n\nMe:...  0.804405   0.098934   
2859   I wish Boris all the best. Will the media rele...  0.093473   0.818201   
3306   We are all gonna have HELLA trust issues when ...  0.757678   0.138887   
3403   My son  19 year old son in Suffolk county NY j...  0.620373   0.212323   
3763   Has this #coronavirus made us all paranoid? I'...  0.807783   0.086507   
3886   My wife was speaking to me and, after 30s of c...  0.828118   0.086940   
4276   I think I relate to this because coping with a...  0.826422   0.087797   
4777   Why did I start watching #pandemic? I feel stu...  0.637099   0.099410   
5451   "I’d be lying if I said that this pandemic did...  0.828118   0.086940   
6240   watching the perks of being a wallflower over ...  0.804405   0.098934   
6372   I miss the days when I used to be able to scro...  0.645397   0.220015   
6587   Three weeks into quarantine and chill, and dam...  0.529368   0.313118   
7326   FYI\nFear of going out of home = Agoraphobia\n...  0.683731   0.207900   
7453   Reason fifty million why it's difficult to be ...  0.825272   0.088379   
7818   Is this #coronavirus-induced shortness of brea...  0.683731   0.207900   
8069   Society right now is my antisocial dreams. Peo...  0.807783   0.086507   
8083   I know this has been a rough couple of weeks a...  0.825272   0.088379   
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...  0.807783   0.086507   
8408   I was confident on day one we would beat it \n...  0.807783   0.086507   
8632   As someone who has experienced anxiety and pan...  0.703240   0.175296   
8746   The Faint - Paranoiattack https://t.co/glhSnMN...  0.711695   0.129751   
8967   One time I was scared and went to the hospital...  0.828118   0.086940   
9120   you know quarantine’s got you depressed af whe...  0.093884   0.512969   
9122   I think I'm going to only focus on local news ...  0.828118   0.086940   
9183   Tbh, the daily updates of #Covid19 had given m...  0.093473   0.818201   
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...  0.093473   0.818201   
9729   Breaking your addiction to #BreakingNews - "It...  0.097188   0.814848   
10358  BBC News - Coronavirus and anxiety: 'Following...  0.534834   0.148253   
10651  I dont know if this is PTSD... but anytime i s...  0.677529   0.082097   
10790  I'm ridiculously chill in emergency situations...  0.683731   0.207900   
11390  Emergency Alert — state of Illinois vs. state ...  0.093473   0.818201   
11489  #Coronavirus and anxiety: 'Following the news ...  0.828118   0.086940   
11563  Anyone else find themselves having little pani...  0.757678   0.138887   
11810  I've just discovered this if you are a #vulner...  0.113261   0.618841   
12257  Hi Everyone-\n\nI, like many, have been suffer...  0.826422   0.087797   
12663  Thank you to @danjlevy and the amazing cast of...  0.828118   0.086940   
12715  I've seen all the charts about the symptoms of...  0.797710   0.102320   
12861  Its 2am. I am having a bad night. Many are hav...  0.782806   0.109859   
13920  Just going to @Target &amp; grocery shopping i...  0.825272   0.088379   
13991  Enough pointless autistic meltdowns. I'm gonna...  0.804405   0.098934   
14670  Things I developed for the first time during t...  0.825272   0.088379   
15070  Donald Trump, the passive-aggressive Sadist So...  0.808583   0.096821   
15100  Reporter Jim @Acosta reads Trump's own words b...  0.508312   0.327127   
15161  One thing people should know: I'm 85, I don’t ...  0.563660   0.290304   
15

In [ ]:
df_discrepancy = df_messy_prob_label[condition1 | condition2] # Equivalent to - df_messy_prob_label[(df_messy_prob_label['cond1'] == 1) | (df_messy_prob_label['cond2'] == 1)]
df_discrepancy

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.683731   0.207900   
538    As someone who has experienced anxiety and pan...  0.678802   0.179644   
920    When you are having a panic attack and one of ...  0.683731   0.207900   
3403   My son  19 year old son in Suffolk county NY j...  0.620373   0.212323   
4777   Why did I start watching #pandemic? I feel stu...  0.637099   0.099410   
6372   I miss the days when I used to be able to scro...  0.645397   0.220015   
6587   Three weeks into quarantine and chill, and dam...  0.529368   0.313118   
7326   FYI\nFear of going out of home = Agoraphobia\n...  0.683731   0.207900   
7818   Is this #coronavirus-induced shortness of brea...  0.683731   0.207900   
9120   you know quarantine’s got you depressed af whe...  0.093884   0.512969   
10358  BBC News - Coronavirus and anxiety: 'Following...  0.534834   0.148253   
10651  I dont know if this is PTSD... but anytime i s...  0.677529   0.082097   
10790  I'm ridiculously chill in emergency situations...  0.683731   0.207900   
11810  I've just discovered this if you are a #vulner...  0.113261   0.618841   
15100  Reporter Jim @Acosta reads Trump's own words b...  0.508312   0.327127   
15161  One thing people should know: I'm 85, I don’t ...  0.563660   0.290304   
15957  Since my anxiety around #coronavirus subsided,...  0.669429   0.214947   

        UN_prob  cond1  cond2  
381    0.108368      1      0  
538    0.141554      1      0  
920    0.108368      1      0  
3403   0.167305      1      0  
4777   0.263491      1      1  
6372   0.134588      1      0  
6587   0.157513      1      1  
7326   0.108368      1      0  
7818   0.108368      1      0  
9120   0.393147      1      1  
10358  0.316913      1      1  
10651  0.240374      1      0  
10790  0.108368      1      0  
11810  0.267898      1      1  
15100  0.164560      1      1  
15161  0.146036      1      1  
15957  0.115624      1      0

In [ ]:
len(df_discrepancy)

17

In [ ]:
df_discrepancy.to_csv('160traintest_liwc_2features_discrepancy.csv')