In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [3]:
df_larger_annotated = pd.read_csv('/content/drive/MyDrive/IDSIA Biomedical Texts/Tweets Project/large16k_with_annotated_part_and_feat_incl_emb.csv')
df_larger_annotated

Unnamed: 0            status_id              user_id  \
0             118  1245863648913813504  1148511375976611840   
1             308  1245863885204152321             20817049   
2             327  1245863937247076353            866442835   
3             482  1245864250700001280   919734991390724096   
4             594  1245864498344296449   895000278201708545   
...           ...                  ...                  ...   
16535     3246439  1248759142933835776            162719860   
16536     3246515  1248759404666765312            381842403   
16537     3247045  1248761313091780609           1621100112   
16538     3247300  1248762191660093451            494002295   
16539     3247370  1248762451539222528           2501039616   

                 created_at  \
0      2020-04-03T00:00:15Z   
1      2020-04-03T00:01:11Z   
2      2020-04-03T00:01:24Z   
3      2020-04-03T00:02:39Z   
4      2020-04-03T00:03:38Z   
...                     ...   
16535  2020-04-10T23:45:55Z   
16536  2020-04-10T23:46:57Z   
16537  2020-04-10T23:54:32Z   
16538  2020-04-10T23:58:02Z   
16539  2020-04-10T23:59:03Z   

                                                    text  panic_kw_count  \
0      Dear World👨‍👩‍👧‍👦, you need not panic, because...               1   
1      .@fordnation says releasing the projection mod...               1   
2      "Neurologists around the world say that a smal...               0   
3      Coronavirus: More than one million cases confi...               0   
4      This is my Gov, @henrymcmaster, today, 4/2/202...               0   
...                                                  ...             ...   
16535  My story about #specialneeds kids &amp; #silve...               0   
16536  Just a quick update: Thursday afternoon, mum h...               0   
16537  #COVID_19 \n•We are all we've got.\n•Don’t giv...               1   
16538  COVID-19 Mental Health Resources from the Coun...               1   
16539  Dear fellow Bostonians, Massachusetts just rec...               0   

       symptoms_ext_count     i  illness  mental  ...  emo_neg  \
0                       0  0.00    12.50    0.00  ...     6.25   
1                       0  0.00     0.00    0.00  ...     3.57   
2                       1  0.00     5.88    0.00  ...     0.00   
3                       0  2.94     5.88    2.94  ...     2.94   
4                       1  2.38     0.00    0.00  ...     0.00   
...                   ...   ...      ...     ...  ...      ...   
16535                   0  3.70    11.11    7.41  ...     3.70   
16536                   0  2.00     8.00    2.00  ...     2.00   
16537                   0  0.00     0.00    0.00  ...     4.55   
16538                   0  0.00     6.25   12.50  ...     6.25   
16539                   1  0.00     0.00    0.00  ...     0.00   

                                  twitter4sse_embeddings used_for_annotation  \
0      [-0.040745142847299576, 0.011479376815259457, ...                   0   
1      [-0.2589869797229767, 0.14035490155220032, 0.0...                   0   
2      [-0.02708950825035572, 0.20832084119319916, -0...                   0   
3      [-0.23723432421684265, 0.072296142578125, -0.2...                   0   
4      [-0.42780137062072754, 0.127772256731987, -0.2...                   0   
...                                                  ...                 ...   
16535  [-0.2954484224319458, -0.21568302810192108, 0....                   0   
16536  [-0.03530991077423096, 0.17665432393550873, -0...                   0   
16537  [-0.20700444281101227, 0.01790219359099865, 0....                   0   
16538  [-0.2529967129230499, 0.08556650578975677, -0....                   0   
16539  [-0.2330004721879959, 0.15653513371944427, 0.0...                   0   

        A1   A2   A3   A4   A5   A6 majority_vote  
0      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
1      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
2      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
3 

In [4]:
# converting embeddings from string to list
df_larger_annotated['twitter4sse_embeddings'] = df_larger_annotated['twitter4sse_embeddings'].apply(lambda x: eval(x))

In [5]:
df_annotated = df_larger_annotated[(df_larger_annotated.used_for_annotation==1) & (df_larger_annotated.majority_vote!="NoMajority")]
df_annotated

Unnamed: 0            status_id              user_id  \
105         21195  1245916048517292033            297944588   
107         21587  1245916935998464005  1116031804165767169   
138         26533  1245928581353467910           3284687677   
172         30413  1245940255993155584  1136453384054034432   
288         50758  1245998640499322881           2677225992   
...           ...                  ...                  ...   
15601     3028959  1250474359715594240   747257810010931201   
15832     3086951  1250568412746612737            256188572   
15838     3088475  1250572544215642112  1172938416125808640   
16087     3144693  1248575471241093120            143915733   
16441     3230828  1248716546656145413             20393302   

                 created_at  \
105    2020-04-03T03:28:28Z   
107    2020-04-03T03:32:00Z   
138    2020-04-03T04:18:16Z   
172    2020-04-03T05:04:40Z   
288    2020-04-03T08:56:40Z   
...                     ...   
15601  2020-04-15T17:21:34Z   
15832  2020-04-15T23:35:18Z   
15838  2020-04-15T23:51:43Z   
16087  2020-04-10T11:36:04Z   
16441  2020-04-10T20:56:39Z   

                                                    text  panic_kw_count  \
105    Fuck you china. I was 2 years clear of severe ...               1   
107    Feeling so off today and I can’t tell if this ...               1   
138    Good lord people we need to stop having people...               1   
172    I'm telling yall, Chill the fuck out!! This Vi...               0   
288    Episode of #CoronaVirus panic. Man took his gl...               1   
...                                                  ...             ...   
15601  I have true compassion for these families, but...               1   
15832  My mom called asked me to come over, she is on...               1   
15838  Having a panic attack while grocery shopping i...               1   
16087  Irresponsible reporting and telling people sha...               1   
16441  Have reverted back to having panic attacks dur...               1   

       symptoms_ext_count      i  illness  mental  ...  emo_neg  \
105                     0  11.54     3.85    7.69  ...    11.54   
107                     0  12.00     4.00    8.00  ...     8.00   
138                     0   9.52     2.38    4.76  ...     4.76   
172                     1   2.33     4.65    2.33  ...     2.33   
288                     1   6.90     1.72    0.00  ...     1.72   
...                   ...    ...      ...     ...  ...      ...   
15601                   0   2.33     2.33    4.65  ...     6.98   
15832                   1  11.11     0.00    3.70  ...     7.41   
15838                   0   9.09     2.27    4.55  ...     6.82   
16087                   1   0.00     5.13    0.00  ...     2.56   
16441                   0   7.14     4.76    4.76  ...     7.14   

                                  twitter4sse_embeddings used_for_annotation  \
105    [-0.22512023150920868, 0.03707732632756233, 0....                   1   
107    [0.010432062670588493, 0.121722012758255, -0.2...                   1   
138    [-0.20182527601718903, 0.24901598691940308, 0....                   1   
172    [0.18443672358989716, 0.22256337106227875, 0.2...                   1   
288    [-0.07753666490316391, -0.44565826654434204, -...                   1   
...                                                  ...                 ...   
15601  [-0.36669501662254333, 0.15450149774551392, -0...                   1   
15832  [-0.0625092014670372, -0.19092148542404175, 0....                   1   
15838  [-0.05952261760830879, -0.3383149802684784, -0...                   1   
16087  [-0.029525309801101685, 0.2843950092792511, -0...                   1   
16441  [-0.1236368715763092, 0.0016770627116784453, -...                   1   

         A1    A2    A3    A4    A5  A6 majority_vote  
105      PP    PP    PP    PP    PP  PP            PP  
107      PP    PP    PP    PP    PP  PP            PP  
138      PP    UN    PP  PONP 

In [39]:
pd.Series([[1,2,3,4,10],[5,6,7,8,20]])

0    [1, 2, 3, 4, 10]
1    [5, 6, 7, 8, 20]
dtype: object

In [41]:
np.mean(np.vstack(pd.Series([[1,2,3,4,10],[5,6,7,8,20]]).values), axis=0)

array([ 3.,  4.,  5.,  6., 15.])

In [42]:
df_annotated[df_annotated['majority_vote'] == 'PP']['twitter4sse_embeddings']

105      [-0.22512023150920868, 0.03707732632756233, 0....
107      [0.010432062670588493, 0.121722012758255, -0.2...
138      [-0.20182527601718903, 0.24901598691940308, 0....
288      [-0.07753666490316391, -0.44565826654434204, -...
948      [-0.2105899602174759, 0.16660533845424652, -0....
                               ...                        
15128    [0.062091246247291565, 0.1609540730714798, -0....
15162    [0.3263324797153473, 0.128920778632164, -0.053...
15538    [0.005656507797539234, 0.06338222324848175, -0...
15838    [-0.05952261760830879, -0.3383149802684784, -0...
16441    [-0.1236368715763092, 0.0016770627116784453, -...
Name: twitter4sse_embeddings, Length: 94, dtype: object

In [47]:
pp_avg_embedding = np.mean(np.vstack(df_annotated[df_annotated['majority_vote'] == 'PP']['twitter4sse_embeddings'].values), axis=0)
pp_avg_embedding

array([-3.98723608e-02,  4.91910093e-02, -1.16867667e-01,  2.10456507e-01,
        3.53490999e-02,  9.22314103e-02,  1.98500923e-02,  3.04844879e-02,
        1.94719912e-01,  1.08089613e-01, -6.17829273e-02,  2.16425398e-01,
        5.90349494e-02, -1.30408966e-01,  2.63403408e-01, -1.04767534e-01,
       -8.53298124e-03,  1.02137056e-01,  2.01731672e-01, -1.07523987e-01,
       -2.83953813e-02,  2.26737004e-02,  1.34426729e-01,  8.85623691e-02,
        2.76208116e-01,  1.27179756e-02,  1.96049943e-01,  7.13562783e-02,
        1.85781677e-01, -3.58235542e-02,  2.87411170e-01,  1.90160707e-01,
       -9.88064662e-02,  1.51082964e-02,  1.91196717e-01, -2.07174546e-01,
        3.36475534e-02,  4.34386063e-01,  2.00045394e-01,  7.74181734e-02,
        7.56809105e-02, -2.25849949e-01,  4.04274098e-01,  1.46431002e-01,
        2.05800952e-01,  8.02753679e-02,  1.58032985e-01, -1.73659324e-01,
        6.26967713e-02, -1.10438626e-01,  4.05310640e-02,  1.84504632e-01,
       -8.98233672e-02,  

In [48]:
len(pp_avg_embedding)

768

In [49]:
ponp_avg_embedding = np.mean(np.vstack(df_annotated[df_annotated['majority_vote'] == 'PONP']['twitter4sse_embeddings'].values), axis=0)

In [50]:
un_avg_embedding = np.mean(np.vstack(df_annotated[df_annotated['majority_vote'] == 'UN']['twitter4sse_embeddings'].values), axis=0)

In [51]:
df_messy = df_larger_annotated[(df_larger_annotated.used_for_annotation==1) & (df_larger_annotated.majority_vote=="NoMajority")]
df_messy.head()

Unnamed: 0            status_id              user_id  \
381        70068  1246056304919097354            361755825   
538       100700  1246091601618837505            427329617   
920       186038  1246189954163761153   917105229467979776   
1137      238381  1249997318109134848             21745651   
2358      504781  1246487955583238145  1058524126724317184   

                created_at                                               text  \
381   2020-04-03T12:45:48Z  NEWS! Conquer Anxiety, Stress and Panic Attack...   
538   2020-04-03T15:06:03Z  As someone who has experienced anxiety and pan...   
920   2020-04-03T21:36:52Z  When you are having a panic attack and one of ...   
1137  2020-04-14T09:45:59Z  Heard countries have done/are considering exte...   
2358  2020-04-04T17:21:01Z  Panic buying, #supplychain shake-ups and compa...   

      panic_kw_count  symptoms_ext_count     i  illness  mental  ...  emo_neg  \
381                1                   0  2.63     2.63    7.89  ...    21.05   
538                1                   0  5.88     5.88    5.88  ...    17.65   
920                1                   1  0.00     3.85    7.69  ...    19.23   
1137               1                   0  2.22     2.22    4.44  ...     2.22   
2358               1                   1  0.00     3.85    0.00  ...     3.85   

                                 twitter4sse_embeddings used_for_annotation  \
381   [-0.25782403349876404, 0.08037050813436508, 0....                   1   
538   [-0.5726941823959351, 0.12105824798345566, 0.1...                   1   
920   [-0.06552565842866898, 0.018419360741972923, -...                   1   
1137  [-0.18501493334770203, 0.13860271871089935, 0....                   1   
2358  [-0.13047395646572113, -0.052925579249858856, ...                   1   

      A1    A2    A3    A4    A5    A6 majority_vote  
381   UN  PONP    UN  PONP    UN  PONP    NoMajority  
538   PP  PONP    PP  PONP  PONP    PP    NoMajority  
920   PP    PP    PP  PONP  PONP  PONP    NoMajority  
1137  PP  PONP     ?    PP     ?     ?    NoMajority  
2358  UN    UN  PONP  PONP  PONP    UN    NoMajority  

[5 rows x 21 columns]

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
type(df_messy['twitter4sse_embeddings'][381])

list

In [67]:
cosine_similarity([df_messy['twitter4sse_embeddings'][381]], [list(pp_avg_embedding)])

array([[0.63464035]])

In [68]:
cosine_similarity([df_messy['twitter4sse_embeddings'][381]], [list(ponp_avg_embedding)])

array([[0.69816439]])

In [66]:
cosine_similarity([df_messy['twitter4sse_embeddings'][381]], [list(un_avg_embedding)])

array([[0.66400129]])

In [70]:
for i in list(df_messy.index):
  print(i, cosine_similarity([df_messy['twitter4sse_embeddings'][i]], [list(pp_avg_embedding)]))
  print(i, cosine_similarity([df_messy['twitter4sse_embeddings'][i]], [list(ponp_avg_embedding)]))
  print(i, cosine_similarity([df_messy['twitter4sse_embeddings'][i]], [list(un_avg_embedding)]))
  print()

381 [[0.63464035]]
381 [[0.69816439]]
381 [[0.66400129]]

538 [[0.78610652]]
538 [[0.83520831]]
538 [[0.79055918]]

920 [[0.85175536]]
920 [[0.86934991]]
920 [[0.77899569]]

1137 [[0.69654272]]
1137 [[0.75423947]]
1137 [[0.66926149]]

2358 [[0.51323531]]
2358 [[0.60697861]]
2358 [[0.60679371]]

2540 [[0.74235902]]
2540 [[0.68854987]]
2540 [[0.66436581]]

2859 [[0.63114415]]
2859 [[0.68692094]]
2859 [[0.63558089]]

3306 [[0.69866911]]
3306 [[0.68334997]]
3306 [[0.59466512]]

3403 [[0.7543396]]
3403 [[0.70046403]]
3403 [[0.67502584]]

3763 [[0.68052264]]
3763 [[0.6211973]]
3763 [[0.64898516]]

3886 [[0.73846618]]
3886 [[0.70734714]]
3886 [[0.69796058]]

4276 [[0.83146696]]
4276 [[0.81848235]]
4276 [[0.7427665]]

4777 [[0.64840562]]
4777 [[0.66898467]]
4777 [[0.62713626]]

5451 [[0.65293334]]
5451 [[0.68329065]]
5451 [[0.65353321]]

6240 [[0.69221653]]
6240 [[0.66577327]]
6240 [[0.65886037]]

6372 [[0.73854383]]
6372 [[0.71684438]]
6372 [[0.64138069]]

6587 [[0.73413928]]
6587 [[0.6875398