In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [4]:
df_larger_annotated = pd.read_csv('/content/drive/MyDrive/IDSIA Biomedical Texts/Tweets Project/large16k_with_annotated_part_and_feat_incl_emb.csv')
df_larger_annotated

Unnamed: 0            status_id              user_id  \
0             118  1245863648913813504  1148511375976611840   
1             308  1245863885204152321             20817049   
2             327  1245863937247076353            866442835   
3             482  1245864250700001280   919734991390724096   
4             594  1245864498344296449   895000278201708545   
...           ...                  ...                  ...   
16535     3246439  1248759142933835776            162719860   
16536     3246515  1248759404666765312            381842403   
16537     3247045  1248761313091780609           1621100112   
16538     3247300  1248762191660093451            494002295   
16539     3247370  1248762451539222528           2501039616   

                 created_at  \
0      2020-04-03T00:00:15Z   
1      2020-04-03T00:01:11Z   
2      2020-04-03T00:01:24Z   
3      2020-04-03T00:02:39Z   
4      2020-04-03T00:03:38Z   
...                     ...   
16535  2020-04-10T23:45:55Z   
16536  2020-04-10T23:46:57Z   
16537  2020-04-10T23:54:32Z   
16538  2020-04-10T23:58:02Z   
16539  2020-04-10T23:59:03Z   

                                                    text  panic_kw_count  \
0      Dear World👨‍👩‍👧‍👦, you need not panic, because...               1   
1      .@fordnation says releasing the projection mod...               1   
2      "Neurologists around the world say that a smal...               0   
3      Coronavirus: More than one million cases confi...               0   
4      This is my Gov, @henrymcmaster, today, 4/2/202...               0   
...                                                  ...             ...   
16535  My story about #specialneeds kids &amp; #silve...               0   
16536  Just a quick update: Thursday afternoon, mum h...               0   
16537  #COVID_19 \n•We are all we've got.\n•Don’t giv...               1   
16538  COVID-19 Mental Health Resources from the Coun...               1   
16539  Dear fellow Bostonians, Massachusetts just rec...               0   

       symptoms_ext_count     i  illness  mental  ...  emo_neg  \
0                       0  0.00    12.50    0.00  ...     6.25   
1                       0  0.00     0.00    0.00  ...     3.57   
2                       1  0.00     5.88    0.00  ...     0.00   
3                       0  2.94     5.88    2.94  ...     2.94   
4                       1  2.38     0.00    0.00  ...     0.00   
...                   ...   ...      ...     ...  ...      ...   
16535                   0  3.70    11.11    7.41  ...     3.70   
16536                   0  2.00     8.00    2.00  ...     2.00   
16537                   0  0.00     0.00    0.00  ...     4.55   
16538                   0  0.00     6.25   12.50  ...     6.25   
16539                   1  0.00     0.00    0.00  ...     0.00   

                                  twitter4sse_embeddings used_for_annotation  \
0      [-0.040745142847299576, 0.011479376815259457, ...                   0   
1      [-0.2589869797229767, 0.14035490155220032, 0.0...                   0   
2      [-0.02708950825035572, 0.20832084119319916, -0...                   0   
3      [-0.23723432421684265, 0.072296142578125, -0.2...                   0   
4      [-0.42780137062072754, 0.127772256731987, -0.2...                   0   
...                                                  ...                 ...   
16535  [-0.2954484224319458, -0.21568302810192108, 0....                   0   
16536  [-0.03530991077423096, 0.17665432393550873, -0...                   0   
16537  [-0.20700444281101227, 0.01790219359099865, 0....                   0   
16538  [-0.2529967129230499, 0.08556650578975677, -0....                   0   
16539  [-0.2330004721879959, 0.15653513371944427, 0.0...                   0   

        A1   A2   A3   A4   A5   A6 majority_vote  
0      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
1      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
2      NaN  NaN  NaN  NaN  NaN  NaN           NaN  
3 

In [5]:
df_larger_annotated[df_larger_annotated['used_for_annotation'] == 1]

Unnamed: 0            status_id              user_id  \
105         21195  1245916048517292033            297944588   
107         21587  1245916935998464005  1116031804165767169   
138         26533  1245928581353467910           3284687677   
172         30413  1245940255993155584  1136453384054034432   
288         50758  1245998640499322881           2677225992   
...           ...                  ...                  ...   
15957     3115183  1248497721775779840             74114924   
16087     3144693  1248575471241093120            143915733   
16305     3197594  1248656868941103104  1224352945833160706   
16441     3230828  1248716546656145413             20393302   
16511     3242099  1248745538079490048             25588808   

                 created_at  \
105    2020-04-03T03:28:28Z   
107    2020-04-03T03:32:00Z   
138    2020-04-03T04:18:16Z   
172    2020-04-03T05:04:40Z   
288    2020-04-03T08:56:40Z   
...                     ...   
15957  2020-04-10T06:27:07Z   
16087  2020-04-10T11:36:04Z   
16305  2020-04-10T16:59:31Z   
16441  2020-04-10T20:56:39Z   
16511  2020-04-10T22:51:51Z   

                                                    text  panic_kw_count  \
105    Fuck you china. I was 2 years clear of severe ...               1   
107    Feeling so off today and I can’t tell if this ...               1   
138    Good lord people we need to stop having people...               1   
172    I'm telling yall, Chill the fuck out!! This Vi...               0   
288    Episode of #CoronaVirus panic. Man took his gl...               1   
...                                                  ...             ...   
15957  Since my anxiety around #coronavirus subsided,...               1   
16087  Irresponsible reporting and telling people sha...               1   
16305  Personally, I don't have a problem with #StayA...               0   
16441  Have reverted back to having panic attacks dur...               1   
16511  haven’t tweeted in 6 months &amp; my thing to ...               1   

       symptoms_ext_count      i  illness  mental  ...  emo_neg  \
105                     0  11.54     3.85    7.69  ...    11.54   
107                     0  12.00     4.00    8.00  ...     8.00   
138                     0   9.52     2.38    4.76  ...     4.76   
172                     1   2.33     4.65    2.33  ...     2.33   
288                     1   6.90     1.72    0.00  ...     1.72   
...                   ...    ...      ...     ...  ...      ...   
15957                   0   6.25     3.13    6.25  ...     9.38   
16087                   1   0.00     5.13    0.00  ...     2.56   
16305                   1   9.09     4.55    9.09  ...     4.55   
16441                   0   7.14     4.76    4.76  ...     7.14   
16511                   0   3.03     3.03    6.06  ...     6.06   

                                  twitter4sse_embeddings used_for_annotation  \
105    [-0.22512023150920868, 0.03707732632756233, 0....                   1   
107    [0.010432062670588493, 0.121722012758255, -0.2...                   1   
138    [-0.20182527601718903, 0.24901598691940308, 0....                   1   
172    [0.18443672358989716, 0.22256337106227875, 0.2...                   1   
288    [-0.07753666490316391, -0.44565826654434204, -...                   1   
...                                                  ...                 ...   
15957  [0.10353126376867294, 0.056257978081703186, -0...                   1   
16087  [-0.029525309801101685, 0.2843950092792511, -0...                   1   
16305  [-0.0216364823281765, 0.2057066708803177, -0.0...                   1   
16441  [-0.1236368715763092, 0.0016770627116784453, -...                   1   
16511  [0.016024738550186157, 0.08114571869373322, 0....                   1   

         A1    A2    A3    A4    A5  A6 majority_vote  
105      PP    PP    PP    PP    PP  PP            PP  
107      PP    PP    PP    PP    PP  PP            PP  
138      PP    UN    PP  PONP 

In [6]:
df_larger_annotated.columns

Index(['Unnamed: 0', 'status_id', 'user_id', 'created_at', 'text',
       'panic_kw_count', 'symptoms_ext_count', 'i', 'illness', 'mental',
       'tone_neg', 'emo_neg', 'twitter4sse_embeddings', 'used_for_annotation',
       'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'majority_vote'],
      dtype='object')

In [7]:
df_larger_annotated['majority_vote'].value_counts()

PP            94
PONP          59
NoMajority    53
UN             7
Name: majority_vote, dtype: int64

## Converting embedding column which is in string to list

In [8]:
df_larger_annotated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16540 entries, 0 to 16539
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Unnamed: 0              16540 non-null  int64  
 1   status_id               16540 non-null  int64  
 2   user_id                 16540 non-null  int64  
 3   created_at              16540 non-null  object 
 4   text                    16540 non-null  object 
 5   panic_kw_count          16540 non-null  int64  
 6   symptoms_ext_count      16540 non-null  int64  
 7   i                       16540 non-null  float64
 8   illness                 16540 non-null  float64
 9   mental                  16540 non-null  float64
 10  tone_neg                16540 non-null  float64
 11  emo_neg                 16540 non-null  float64
 12  twitter4sse_embeddings  16540 non-null  object 
 13  used_for_annotation     16540 non-null  int64  
 14  A1                      213 non-null  

In [9]:
df_larger_annotated['twitter4sse_embeddings'] = df_larger_annotated['twitter4sse_embeddings'].apply(lambda x: eval(x))

In [10]:
type(df_larger_annotated['twitter4sse_embeddings'][0])

list

In [11]:
df_annotated = df_larger_annotated[(df_larger_annotated.used_for_annotation==1) & (df_larger_annotated.majority_vote!="NoMajority")]
df_annotated

Unnamed: 0            status_id              user_id  \
105         21195  1245916048517292033            297944588   
107         21587  1245916935998464005  1116031804165767169   
138         26533  1245928581353467910           3284687677   
172         30413  1245940255993155584  1136453384054034432   
288         50758  1245998640499322881           2677225992   
...           ...                  ...                  ...   
15601     3028959  1250474359715594240   747257810010931201   
15832     3086951  1250568412746612737            256188572   
15838     3088475  1250572544215642112  1172938416125808640   
16087     3144693  1248575471241093120            143915733   
16441     3230828  1248716546656145413             20393302   

                 created_at  \
105    2020-04-03T03:28:28Z   
107    2020-04-03T03:32:00Z   
138    2020-04-03T04:18:16Z   
172    2020-04-03T05:04:40Z   
288    2020-04-03T08:56:40Z   
...                     ...   
15601  2020-04-15T17:21:34Z   
15832  2020-04-15T23:35:18Z   
15838  2020-04-15T23:51:43Z   
16087  2020-04-10T11:36:04Z   
16441  2020-04-10T20:56:39Z   

                                                    text  panic_kw_count  \
105    Fuck you china. I was 2 years clear of severe ...               1   
107    Feeling so off today and I can’t tell if this ...               1   
138    Good lord people we need to stop having people...               1   
172    I'm telling yall, Chill the fuck out!! This Vi...               0   
288    Episode of #CoronaVirus panic. Man took his gl...               1   
...                                                  ...             ...   
15601  I have true compassion for these families, but...               1   
15832  My mom called asked me to come over, she is on...               1   
15838  Having a panic attack while grocery shopping i...               1   
16087  Irresponsible reporting and telling people sha...               1   
16441  Have reverted back to having panic attacks dur...               1   

       symptoms_ext_count      i  illness  mental  ...  emo_neg  \
105                     0  11.54     3.85    7.69  ...    11.54   
107                     0  12.00     4.00    8.00  ...     8.00   
138                     0   9.52     2.38    4.76  ...     4.76   
172                     1   2.33     4.65    2.33  ...     2.33   
288                     1   6.90     1.72    0.00  ...     1.72   
...                   ...    ...      ...     ...  ...      ...   
15601                   0   2.33     2.33    4.65  ...     6.98   
15832                   1  11.11     0.00    3.70  ...     7.41   
15838                   0   9.09     2.27    4.55  ...     6.82   
16087                   1   0.00     5.13    0.00  ...     2.56   
16441                   0   7.14     4.76    4.76  ...     7.14   

                                  twitter4sse_embeddings used_for_annotation  \
105    [-0.22512023150920868, 0.03707732632756233, 0....                   1   
107    [0.010432062670588493, 0.121722012758255, -0.2...                   1   
138    [-0.20182527601718903, 0.24901598691940308, 0....                   1   
172    [0.18443672358989716, 0.22256337106227875, 0.2...                   1   
288    [-0.07753666490316391, -0.44565826654434204, -...                   1   
...                                                  ...                 ...   
15601  [-0.36669501662254333, 0.15450149774551392, -0...                   1   
15832  [-0.0625092014670372, -0.19092148542404175, 0....                   1   
15838  [-0.05952261760830879, -0.3383149802684784, -0...                   1   
16087  [-0.029525309801101685, 0.2843950092792511, -0...                   1   
16441  [-0.1236368715763092, 0.0016770627116784453, -...                   1   

         A1    A2    A3    A4    A5  A6 majority_vote  
105      PP    PP    PP    PP    PP  PP            PP  
107      PP    PP    PP    PP    PP  PP            PP  
138      PP    UN    PP  PONP 

### Label Encoding "Majority Vote" column

In [12]:
from sklearn.preprocessing import LabelEncoder
label_mapping = {"PP": 0, "PONP": 1, "UN": 2}
le = LabelEncoder()
le.fit_transform(list(label_mapping.values()))
df_annotated['label'] = df_annotated['majority_vote'].map(label_mapping)

<ipython-input-12-f820b59bb32b>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_annotated['label'] = df_annotated['majority_vote'].map(label_mapping)


In [13]:
for label, encoded_value in label_mapping.items():
    print(f"Label: {label} - Encoded value: {encoded_value}")

Label: PP - Encoded value: 0
Label: PONP - Encoded value: 1
Label: UN - Encoded value: 2


In [14]:
df_annotated.head()

Unnamed: 0            status_id              user_id  \
105       21195  1245916048517292033            297944588   
107       21587  1245916935998464005  1116031804165767169   
138       26533  1245928581353467910           3284687677   
172       30413  1245940255993155584  1136453384054034432   
288       50758  1245998640499322881           2677225992   

               created_at                                               text  \
105  2020-04-03T03:28:28Z  Fuck you china. I was 2 years clear of severe ...   
107  2020-04-03T03:32:00Z  Feeling so off today and I can’t tell if this ...   
138  2020-04-03T04:18:16Z  Good lord people we need to stop having people...   
172  2020-04-03T05:04:40Z  I'm telling yall, Chill the fuck out!! This Vi...   
288  2020-04-03T08:56:40Z  Episode of #CoronaVirus panic. Man took his gl...   

     panic_kw_count  symptoms_ext_count      i  illness  mental  ...  \
105               1                   0  11.54     3.85    7.69  ...   
107               1                   0  12.00     4.00    8.00  ...   
138               1                   0   9.52     2.38    4.76  ...   
172               0                   1   2.33     4.65    2.33  ...   
288               1                   1   6.90     1.72    0.00  ...   

                                twitter4sse_embeddings  used_for_annotation  \
105  [-0.22512023150920868, 0.03707732632756233, 0....                    1   
107  [0.010432062670588493, 0.121722012758255, -0.2...                    1   
138  [-0.20182527601718903, 0.24901598691940308, 0....                    1   
172  [0.18443672358989716, 0.22256337106227875, 0.2...                    1   
288  [-0.07753666490316391, -0.44565826654434204, -...                    1   

       A1    A2    A3    A4    A5  A6 majority_vote label  
105    PP    PP    PP    PP    PP  PP            PP     0  
107    PP    PP    PP    PP    PP  PP            PP     0  
138    PP    UN    PP  PONP    PP  PP            PP     0  
172  PONP  PONP  PONP  PONP  PONP  PP          PONP     1  
288    PP    PP    PP    PP    PP  PP            PP     0  

[5 rows x 22 columns]

### Standardization of LIWC features

In [15]:
df_annotated.columns

Index(['Unnamed: 0', 'status_id', 'user_id', 'created_at', 'text',
       'panic_kw_count', 'symptoms_ext_count', 'i', 'illness', 'mental',
       'tone_neg', 'emo_neg', 'twitter4sse_embeddings', 'used_for_annotation',
       'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'majority_vote', 'label'],
      dtype='object')

In [16]:
df_annotated[['i','illness', 'mental', 'tone_neg', 'emo_neg']]

i  illness  mental  tone_neg  emo_neg
105    11.54     3.85    7.69     26.92    11.54
107    12.00     4.00    8.00      8.00     8.00
138     9.52     2.38    4.76      7.14     4.76
172     2.33     4.65    2.33      6.98     2.33
288     6.90     1.72    0.00      3.45     1.72
...      ...      ...     ...       ...      ...
15601   2.33     2.33    4.65     13.95     6.98
15832  11.11     0.00    3.70      7.41     7.41
15838   9.09     2.27    4.55      9.09     6.82
16087   0.00     5.13    0.00      5.13     2.56
16441   7.14     4.76    4.76      7.14     7.14

[160 rows x 5 columns]

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [18]:
standardized_liwc = sc.fit_transform(df_annotated[['i','illness', 'mental', 'tone_neg', 'emo_neg']])

In [19]:
standardized_liwc

array([[ 1.04879875e+00, -7.72953559e-02,  7.78759369e-01,
         2.89145158e+00,  5.86838072e-01],
       [ 1.14686465e+00, -2.41104780e-02,  8.65488301e-01,
        -2.99290140e-01, -3.60841791e-02],
       [ 6.18161564e-01, -5.98507160e-01, -4.09689292e-02,
        -4.44323854e-01, -6.06216409e-01],
       [-9.14651004e-01,  2.06357326e-01, -7.20811852e-01,
        -4.71306871e-01, -1.03381558e+00],
       [ 5.96123386e-02, -8.32520623e-01, -1.37267770e+00,
        -1.06661968e+00, -1.14115529e+00],
       [-9.48760881e-01, -6.72965989e-01, -7.65575172e-01,
        -5.48883044e-01, -6.78362771e-01],
       [-1.41137608e+00, -5.09865697e-01, -1.37267770e+00,
         5.70912147e-01,  4.09111667e-01],
       [ 2.28029853e-01, -7.72953559e-02, -2.95560312e-01,
        -9.99162134e-01, -7.66346140e-01],
       [-6.50299463e-01, -1.44237389e+00, -3.73896122e-01,
         1.57734705e-01,  4.40785680e-01],
       [ 2.70667198e-01, -5.09865697e-01,  9.89164459e-02,
        -7.61374300e-01

In [20]:
df_annotated['label'].value_counts()

0    94
1    59
2     7
Name: label, dtype: int64

### XGB

In [21]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import xgboost as xgb
from sklearn.metrics import roc_auc_score, make_scorer # not able to import balanced_accuray_score
from sklearn.model_selection import GridSearchCV # cross validation, used for hyperparamter tuning
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import f1_score, classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve, auc
import seaborn as sns

### XGB with Emb

In [23]:
X = np.array(df_annotated['twitter4sse_embeddings'].tolist())    # run this for only embeddings

#X = np.concatenate((    standardized_liwc, np.array(df_annotated['twitter4sse_embeddings'].tolist())   ), axis=1)    # run this for emb + only liwc

#emb_liwc = np.concatenate((    standardized_liwc, np.array(df_annotated['twitter4sse_embeddings'].tolist())   ), axis=1)   # run these 2 for emb + liwc + 2 features
#X = np.concatenate(  (df_annotated[['panic_kw_count', 'symptoms_ext_count']].values, emb_liwc    ), axis=1)


y = np.array(df_annotated['label'])

In [24]:
X

array([[-2.25120232e-01,  3.70773263e-02,  3.17902528e-02, ...,
        -4.30038571e-02,  1.49781048e-01, -5.37211038e-02],
       [ 1.04320627e-02,  1.21722013e-01, -2.69894660e-01, ...,
         2.98047848e-02,  3.91920984e-01,  4.32758518e-02],
       [-2.01825276e-01,  2.49015987e-01,  5.97718619e-02, ...,
         2.95174539e-01,  2.75589973e-01,  2.05261290e-01],
       ...,
       [-5.95226176e-02, -3.38314980e-01, -8.80411789e-02, ...,
        -1.57644153e-01,  5.35904020e-02, -4.30524647e-02],
       [-2.95253098e-02,  2.84395009e-01, -1.44363359e-01, ...,
         4.79702749e-06,  3.48803520e-01, -2.18136534e-01],
       [-1.23636872e-01,  1.67706271e-03, -1.11626983e-01, ...,
        -2.22300664e-01,  2.22533271e-01,  1.02165766e-01]])

In [25]:
X.shape

(160, 768)

In [26]:
#clf_xgb = xgb.XGBClassifier(objective='binary:logistic', missing=0, seed=42) # missing=None not working
clf_xgb = xgb.XGBClassifier(objective='multi:softmax', missing=0, seed=42, num_class=3)

In [27]:
# Ref - https://towardsdatascience.com/micro-macro-weighted-averages-of-f1-score-clearly-explained-b603420b292f
xgb_f1scores = []
xgb_micro_f1scores = []
xgb_macro_f1scores = []
xgb_rocaucscore = []
xgb_praucscore = []

for train_index, test_index in folds.split(X, y):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]

    # XGBoost
    clf_xgb.fit(X_train, y_train,
              verbose=False,  # set to True for individual use
              early_stopping_rounds=10,
              #eval_metrics='aucpr',
              eval_set = [(X_test,y_test)])
    y_pred = clf_xgb.predict(X_test)

    f1 = f1_score(y_test, y_pred,average='weighted')
    xgb_f1scores.append(f1)

    micro_f1 = f1_score(y_test, y_pred, average='micro')
    xgb_micro_f1scores.append(micro_f1)

    macro_f1 = f1_score(y_test, y_pred, average='macro')
    xgb_macro_f1scores.append(macro_f1)

    # class_report = classification_report(y_test, y_pred)   # this will print reports of all 10 different sets of folds
    # print(class_report)

    # cm = confusion_matrix(y_test, y_pred)    # this will print CMs of all 10 different sets of folds
    # plt.figure(figsize=(8, 6))
    # labels = ['PO', 'PONP', 'UN']
    # sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
    # plt.xlabel('Predicted')
    # plt.ylabel('True')
    # plt.title('Emb + only LIWC Confusion Matrix')
    # plt.show()

    #rocaucscore = roc_auc_score(y_test, y_pred, multi_class='ovr')
    #xgb_rocaucscore.append(rocaucscore)

    # print(y_test.shape, y_pred.shape)
    # y_pred_prob = clf_xgb.predict_proba(X_test)
    # print(np.unique(y_test))
    # print(y_pred_prob.shape[1])
    # rocaucscore = roc_auc_score(y_test, y_pred_prob, multi_class='ovo')

    # precision, recall, thresholds = precision_recall_curve(y_test, y_pred)  # Compute precision, recall, and thresholds
    # pr_auc = auc(recall, precision)  # Calculate PR-AUC
    # xgb_praucscore.append(pr_auc)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-

In [28]:
print(xgb_f1scores)
print(np.mean(xgb_f1scores))
print(np.std(xgb_f1scores))

[0.9361471861471862, 0.876984126984127, 0.8681818181818182, 0.7196969696969696, 0.8453947368421053, 0.7861842105263158, 0.7884615384615384, 0.73109243697479, 0.7789772727272727, 0.9086538461538461]
0.8239774142695969
0.07013654184066542


In [29]:
print(xgb_micro_f1scores)
print(np.mean(xgb_micro_f1scores))
print(np.std(xgb_micro_f1scores))

[0.9375, 0.875, 0.875, 0.75, 0.875, 0.8125, 0.8125, 0.75, 0.8125, 0.9375]
0.84375
0.0640434422872475


In [30]:
print(xgb_macro_f1scores)
print(np.mean(xgb_macro_f1scores))
print(np.std(xgb_macro_f1scores))

[0.9307359307359306, 0.873015873015873, 0.8545454545454545, 0.494949494949495, 0.5935672514619883, 0.5584795321637427, 0.5527065527065527, 0.5126050420168068, 0.5424242424242424, 0.641025641025641]
0.6554055015045727
0.1567460281131972


In [ ]:
# print(xgb_rocaucscore)
# print(np.mean(xgb_rocaucscore))
# print(np.std(xgb_rocaucscore))

In [ ]:
# print(xgb_praucscore)
# print(np.mean(xgb_praucscore))
# print(np.std(xgb_praucscore))

In [ ]:
# proof that the model does predict 2 (UN) label also
for i in range(10):
  print(clf_xgb.predict([df_larger_annotated['twitter4sse_embeddings'][i]]))
  print(clf_xgb.predict_proba([df_larger_annotated['twitter4sse_embeddings'][i]]))

[1]
[[0.39645815 0.52416766 0.07937422]]
[0]
[[0.5682018  0.36896476 0.06283341]]
[1]
[[0.2626604  0.64765173 0.08968789]]
[1]
[[0.29631352 0.58910304 0.11458348]]
[1]
[[0.1546324  0.7759632  0.06940448]]
[1]
[[0.40754566 0.53594214 0.05651218]]
[1]
[[0.1650397  0.7524085  0.08255178]]
[1]
[[0.26048476 0.6684122  0.07110306]]
[1]
[[0.06642516 0.8936241  0.03995065]]
[1]
[[0.13097708 0.81100434 0.05801857]]


### Ignore

In [ ]:
X = np.array(df_annotated['twitter4sse_embeddings'].to_list())
y = np.array(df_annotated['label'])

In [ ]:
X

array([[-2.25120232e-01,  3.70773263e-02,  3.17902528e-02, ...,
        -4.30038571e-02,  1.49781048e-01, -5.37211038e-02],
       [ 1.04320627e-02,  1.21722013e-01, -2.69894660e-01, ...,
         2.98047848e-02,  3.91920984e-01,  4.32758518e-02],
       [-2.01825276e-01,  2.49015987e-01,  5.97718619e-02, ...,
         2.95174539e-01,  2.75589973e-01,  2.05261290e-01],
       ...,
       [-5.95226176e-02, -3.38314980e-01, -8.80411789e-02, ...,
        -1.57644153e-01,  5.35904020e-02, -4.30524647e-02],
       [-2.95253098e-02,  2.84395009e-01, -1.44363359e-01, ...,
         4.79702749e-06,  3.48803520e-01, -2.18136534e-01],
       [-1.23636872e-01,  1.67706271e-03, -1.11626983e-01, ...,
        -2.22300664e-01,  2.22533271e-01,  1.02165766e-01]])

In [ ]:
len(X), len(X[0])

(160, 768)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None, stratify = y)

In [ ]:
# # Converting all to 2D
# X_train = X_train.values.reshape(-1,1)
# y_train = y_train.values.reshape(-1,1)
# X_test = X_test.values.reshape(-1,1)
# y_test = y_test.values.reshape(-1,1)

In [ ]:
clf_xgbtrial = xgb.XGBClassifier(objective='binary:logistic', missing=0, seed=42)

In [ ]:
clf_xgbtrial = xgb.XGBClassifier(objective='multi:softmax', missing=0, seed=42, num_class=3)

In [ ]:
clf_xgbtrial = xgb.XGBClassifier(objective='multi:softprob', missing=0, seed=42, num_class=3)

In [ ]:
clf_xgbtrial.fit(X_train, y_train,
              verbose=False,  # set to True for individual use
              early_stopping_rounds=10,
              #eval_metrics='aucpr',
              eval_set = [(X_test,y_test)])

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=0, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_class=3,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [ ]:
clf_xgbtrial.predict([np.array(df_larger_annotated['twitter4sse_embeddings'][0])])

array([1])

In [ ]:
for i in range(10):
  print(clf_xgbtrial.predict([df_larger_annotated['twitter4sse_embeddings'][i]]))
  print(clf_xgbtrial.predict_proba([df_larger_annotated['twitter4sse_embeddings'][i]]))

[1]
[[0.04106402 0.9217991  0.03713684]]
[0]
[[0.5084511  0.34997576 0.14157312]]
[2]
[[0.09202711 0.38705197 0.5209209 ]]
[0]
[[0.86973083 0.06710157 0.06316756]]
[0]
[[0.68987304 0.22916467 0.08096224]]
[1]
[[0.10174033 0.667774   0.23048568]]
[1]
[[0.04896858 0.8381388  0.11289257]]
[0]
[[0.6560702  0.22121851 0.12271132]]
[2]
[[0.10455995 0.38553032 0.50990975]]
[0]
[[0.83318996 0.08592378 0.08088627]]


In [ ]:
import numpy as np
import xgboost as xgb

# Example data
X = np.random.randn(10, 5)  # 10 samples, 5 features
y = np.random.randint(0, 3, 10)  # 3 classes

# Create the XGBoost DMatrix
dtrain = xgb.DMatrix(X, label=y)

# Set the XGBoost parameters
params = {
    'objective': 'multi:softmax',
    'num_class': 3
}

# Train the XGBoost model
model_softmax = xgb.train(params, dtrain)

# Predict using multi:softmax
y_pred_softmax = model_softmax.predict(dtrain)

# Set the XGBoost parameters for multi:softprob
params['objective'] = 'multi:softprob'

# Train the XGBoost model with multi:softprob
model_softprob = xgb.train(params, dtrain)

# Predict using multi:softprob
y_pred_softprob = model_softprob.predict(dtrain)

# Print the outputs
print("Predictions using multi:softmax:")
print(y_pred_softmax)
print("Predictions using multi:softprob:")
print(y_pred_softprob)


Predictions using multi:softmax:
[0. 1. 0. 1. 0. 2. 2. 2. 0. 2.]
Predictions using multi:softprob:
[[0.7572623  0.1752327  0.06750501]
 [0.13126607 0.6804327  0.18830131]
 [0.7668154  0.17744331 0.05574123]
 [0.15108883 0.6926127  0.15629849]
 [0.7346571  0.04288264 0.22246026]
 [0.13268174 0.07888183 0.7884364 ]
 [0.16424914 0.10219272 0.7335582 ]
 [0.1628676  0.13529077 0.7018416 ]
 [0.5279136  0.18384962 0.28823683]
 [0.18762141 0.07388511 0.7384935 ]]


### Testing model on Messy dataset and gettiing discrepancies

In [ ]:
df_messy = df_larger_annotated[(df_larger_annotated.used_for_annotation==1) & (df_larger_annotated.majority_vote=="NoMajority")]
df_messy.head()

Unnamed: 0            status_id              user_id  \
381        70068  1246056304919097354            361755825   
538       100700  1246091601618837505            427329617   
920       186038  1246189954163761153   917105229467979776   
1137      238381  1249997318109134848             21745651   
2358      504781  1246487955583238145  1058524126724317184   

                created_at                                               text  \
381   2020-04-03T12:45:48Z  NEWS! Conquer Anxiety, Stress and Panic Attack...   
538   2020-04-03T15:06:03Z  As someone who has experienced anxiety and pan...   
920   2020-04-03T21:36:52Z  When you are having a panic attack and one of ...   
1137  2020-04-14T09:45:59Z  Heard countries have done/are considering exte...   
2358  2020-04-04T17:21:01Z  Panic buying, #supplychain shake-ups and compa...   

      panic_kw_count  symptoms_ext_count     i  illness  mental  tone_neg  \
381                1                   0  2.63     2.63    7.89     21.05   
538                1                   0  5.88     5.88    5.88     17.65   
920                1                   1  0.00     3.85    7.69     19.23   
1137               1                   0  2.22     2.22    4.44      2.22   
2358               1                   1  0.00     3.85    0.00      7.69   

      emo_neg                             twitter4sse_embeddings  \
381     21.05  [-0.25782403349876404, 0.08037050813436508, 0....   
538     17.65  [-0.5726941823959351, 0.12105824798345566, 0.1...   
920     19.23  [-0.06552565842866898, 0.018419360741972923, -...   
1137     2.22  [-0.18501493334770203, 0.13860271871089935, 0....   
2358     3.85  [-0.13047395646572113, -0.052925579249858856, ...   

      used_for_annotation  A1    A2    A3    A4    A5    A6 majority_vote  
381                     1  UN  PONP    UN  PONP    UN  PONP    NoMajority  
538                     1  PP  PONP    PP  PONP  PONP    PP    NoMajority  
920                     1  PP    PP    PP  PONP  PONP  PONP    NoMajority  
1137                    1  PP  PONP     ?    PP     ?     ?    NoMajority  
2358                    1  UN    UN  PONP  PONP  PONP    UN    NoMajority

In [ ]:
clf_xgb.predict([df_messy['twitter4sse_embeddings'][381]])

array([1], dtype=int32)

In [ ]:
clf_xgb.predict_proba([df_messy['twitter4sse_embeddings'][381]])

array([[0.38510552, 0.5285045 , 0.08638997]], dtype=float32)

In [ ]:
# df_messy_prob_label = pd.DataFrame(index=df_messy.index)   # empty dataframe with index those of messy dataframe

In [ ]:
df_messy_prob_label = df_messy[['text']]
df_messy_prob_label

text
381    NEWS! Conquer Anxiety, Stress and Panic Attack...
538    As someone who has experienced anxiety and pan...
920    When you are having a panic attack and one of ...
1137   Heard countries have done/are considering exte...
2358   Panic buying, #supplychain shake-ups and compa...
2540   Me: Yay! #Saturday!\n\nMy #Anxiety: Hi!\n\nMe:...
2859   I wish Boris all the best. Will the media rele...
3306   We are all gonna have HELLA trust issues when ...
3403   My son  19 year old son in Suffolk county NY j...
3763   Has this #coronavirus made us all paranoid? I'...
3886   My wife was speaking to me and, after 30s of c...
4276   I think I relate to this because coping with a...
4777   Why did I start watching #pandemic? I feel stu...
5451   "I’d be lying if I said that this pandemic did...
6240   watching the perks of being a wallflower over ...
6372   I miss the days when I used to be able to scro...
6587   Three weeks into quarantine and chill, and dam...
7326   FYI\nFear of going out of home = Agoraphobia\n...
7453   Reason fifty million why it's difficult to be ...
7818   Is this #coronavirus-induced shortness of brea...
8069   Society right now is my antisocial dreams. Peo...
8083   I know this has been a rough couple of weeks a...
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...
8408   I was confident on day one we would beat it \n...
8632   As someone who has experienced anxiety and pan...
8746   The Faint - Paranoiattack https://t.co/glhSnMN...
8967   One time I was scared and went to the hospital...
9120   you know quarantine’s got you depressed af whe...
9122   I think I'm going to only focus on local news ...
9183   Tbh, the daily updates of #Covid19 had given m...
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...
9729   Breaking your addiction to #BreakingNews - "It...
10358  BBC News - Coronavirus and anxiety: 'Following...
10651  I dont know if this is PTSD... but anytime i s...
10790  I'm ridiculously chill in emergency situations...
11390  Emergency Alert — state of Illinois vs. state ...
11489  #Coronavirus and anxiety: 'Following the news ...
11563  Anyone else find themselves having little pani...
11810  I've just discovered this if you are a #vulner...
12257  Hi Everyone-\n\nI, like many, have been suffer...
12663  Thank you to @danjlevy and the amazing cast of...
12715  I've seen all the charts about the symptoms of...
12861  Its 2am. I am having a bad night. Many are hav...
13920  Just going to @Target &amp; grocery shopping i...
13991  Enough pointless autistic meltdowns. I'm gonna...
14670  Things I developed for the first time during t...
15070  Donald Trump, the passive-aggressive Sadist So...
15100  Reporter Jim @Acosta reads Trump's own words b...
15161  One thing people should know: I'm 85, I don’t ...
15613  Panic attacks, diarrhea, obsessive list making...
15957  Since my anxiety around #coronavirus subsided,...
16305  Personally, I don't have a problem with #StayA...
16511  haven’t tweeted in 6 months &amp; my thing to ...

In [ ]:
# run for only emb
a = df_messy['twitter4sse_embeddings'].apply(lambda x: clf_xgb.predict_proba([x]))
a = pd.DataFrame(a)
a

# run for emb+liwc
# a = clf_xgb.predict_proba(   np.concatenate((    messy_standardized_liwc, np.array(df_messy['twitter4sse_embeddings'].tolist())   ), axis=1)        )
# a = pd.DataFrame(a, columns=['PP', 'PONP', 'UN'])
# a

# run these 2 for emb + liwc + 2 features
# messy_emb_liwc = np.concatenate((    messy_standardized_liwc, np.array(df_messy['twitter4sse_embeddings'].tolist())   ), axis=1)
# X = np.concatenate(  (df_messy[['panic_kw_count', 'symptoms_ext_count']].values, messy_emb_liwc    ), axis=1)
# a = clf_xgb.predict_proba(X)
# a = pd.DataFrame(a, columns=['PP', 'PONP', 'UN'])
# a

twitter4sse_embeddings
381     [[0.38510552, 0.5285045, 0.086389974]]
538     [[0.3149209, 0.60789263, 0.077186465]]
920       [[0.40620252, 0.4934516, 0.1003459]]
1137        [[0.591747, 0.3473454, 0.0609076]]
2358      [[0.4534108, 0.5051833, 0.04140592]]
2540      [[0.1293803, 0.8058562, 0.06476346]]
2859    [[0.13443017, 0.77970535, 0.08586453]]
3306    [[0.10465412, 0.8429469, 0.052399017]]
3403     [[0.2322777, 0.6537876, 0.113934666]]
3763   [[0.13264807, 0.83840376, 0.028948152]]
3886     [[0.110499054, 0.804144, 0.08535686]]
4276     [[0.13727102, 0.7497729, 0.11295609]]
4777   [[0.50241363, 0.45556393, 0.042022448]]
5451   [[0.51684576, 0.42975655, 0.053397734]]
6240     [[0.1501605, 0.80115646, 0.04868302]]
6372   [[0.17283127, 0.72641194, 0.100756764]]
6587    [[0.26227722, 0.58938575, 0.14833708]]
7326     [[0.23011239, 0.7085487, 0.06133887]]
7453     [[0.13673629, 0.7932863, 0.06997736]]
7818    [[0.19338626, 0.7280869, 0.078526855]]
8069     [[0.26632884, 0.6539515, 0.07971967]]
8083     [[0.43990552, 0.4894778, 0.07061669]]
8192   [[0.52039737, 0.39474583, 0.084856845]]
8408      [[0.415107, 0.5394552, 0.045437794]]
8632     [[0.6132621, 0.31704518, 0.06969269]]
8746   [[0.43910718, 0.49430868, 0.066584125]]
8967    [[0.24771856, 0.6529346, 0.099346854]]
9120    [[0.1939807, 0.71711683, 0.088902466]]
9122     [[0.13977337, 0.7561357, 0.10409096]]
9183    [[0.3118256, 0.57542807, 0.112746276]]
9445    [[0.54212344, 0.40769267, 0.05018393]]
9729    [[0.07759086, 0.8623536, 0.060055505]]
10358    [[0.13040625, 0.7678277, 0.10176605]]
10651    [[0.1187881, 0.80197746, 0.07923446]]
10790  [[0.14338554, 0.76270515, 0.093909346]]
11390    [[0.35756212, 0.5661323, 0.07630561]]
11489     [[0.4096449, 0.50087976, 0.0894753]]
11563   [[0.15534478, 0.7991988, 0.045456443]]
11810   [[0.20140836, 0.7552899, 0.043301728]]
12257   [[0.4724499, 0.46710745, 0.060442593]]
12663     [[0.502467, 0.40514696, 0.09238609]]
12715   [[0.23912556, 0.6659708, 0.094903626]]
12861  [[0.40430647, 0.52092946, 0.074764065]]
13920   [[0.1315087, 0.81210124, 0.056390077]]
13991     [[0.4396147, 0.4952673, 0.06511797]]
14670  [[0.06994391, 0.85967404, 0.070382096]]
15070   [[0.3363335, 0.63127816, 0.032388296]]
15100  [[0.065969385, 0.8791806, 0.054849997]]
15161   [[0.39200068, 0.54915684, 0.05884245]]
15613     [[0.0944562, 0.8353153, 0.07022853]]
15957      [[0.3657687, 0.54197025, 0.092261]]
16305   [[0.18440105, 0.70066947, 0.11492956]]
16511   [[0.46644315, 0.46108598, 0.07247086]]

In [ ]:
df_messy_prob_label['PP_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][0])
df_messy_prob_label['PONP_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][1])
df_messy_prob_label['UN_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][2])

<ipython-input-196-731e0c9729f3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['PP_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][0])
<ipython-input-196-731e0c9729f3>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['PONP_prob'] = a['twitter4sse_embeddings'].apply(lambda x: x[0][1])
<ipython-input-196-731e0c9729f3>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = valu

In [ ]:
df_messy_prob_label

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.385106   0.528504   
538    As someone who has experienced anxiety and pan...  0.314921   0.607893   
920    When you are having a panic attack and one of ...  0.406203   0.493452   
1137   Heard countries have done/are considering exte...  0.591747   0.347345   
2358   Panic buying, #supplychain shake-ups and compa...  0.453411   0.505183   
2540   Me: Yay! #Saturday!\n\nMy #Anxiety: Hi!\n\nMe:...  0.129380   0.805856   
2859   I wish Boris all the best. Will the media rele...  0.134430   0.779705   
3306   We are all gonna have HELLA trust issues when ...  0.104654   0.842947   
3403   My son  19 year old son in Suffolk county NY j...  0.232278   0.653788   
3763   Has this #coronavirus made us all paranoid? I'...  0.132648   0.838404   
3886   My wife was speaking to me and, after 30s of c...  0.110499   0.804144   
4276   I think I relate to this because coping with a...  0.137271   0.749773   
4777   Why did I start watching #pandemic? I feel stu...  0.502414   0.455564   
5451   "I’d be lying if I said that this pandemic did...  0.516846   0.429757   
6240   watching the perks of being a wallflower over ...  0.150161   0.801156   
6372   I miss the days when I used to be able to scro...  0.172831   0.726412   
6587   Three weeks into quarantine and chill, and dam...  0.262277   0.589386   
7326   FYI\nFear of going out of home = Agoraphobia\n...  0.230112   0.708549   
7453   Reason fifty million why it's difficult to be ...  0.136736   0.793286   
7818   Is this #coronavirus-induced shortness of brea...  0.193386   0.728087   
8069   Society right now is my antisocial dreams. Peo...  0.266329   0.653952   
8083   I know this has been a rough couple of weeks a...  0.439906   0.489478   
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...  0.520397   0.394746   
8408   I was confident on day one we would beat it \n...  0.415107   0.539455   
8632   As someone who has experienced anxiety and pan...  0.613262   0.317045   
8746   The Faint - Paranoiattack https://t.co/glhSnMN...  0.439107   0.494309   
8967   One time I was scared and went to the hospital...  0.247719   0.652935   
9120   you know quarantine’s got you depressed af whe...  0.193981   0.717117   
9122   I think I'm going to only focus on local news ...  0.139773   0.756136   
9183   Tbh, the daily updates of #Covid19 had given m...  0.311826   0.575428   
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...  0.542123   0.407693   
9729   Breaking your addiction to #BreakingNews - "It...  0.077591   0.862354   
10358  BBC News - Coronavirus and anxiety: 'Following...  0.130406   0.767828   
10651  I dont know if this is PTSD... but anytime i s...  0.118788   0.801977   
10790  I'm ridiculously chill in emergency situations...  0.143386   0.762705   
11390  Emergency Alert — state of Illinois vs. state ...  0.357562   0.566132   
11489  #Coronavirus and anxiety: 'Following the news ...  0.409645   0.500880   
11563  Anyone else find themselves having little pani...  0.155345   0.799199   
11810  I've just discovered this if you are a #vulner...  0.201408   0.755290   
12257  Hi Everyone-\n\nI, like many, have been suffer...  0.472450   0.467107   
12663  Thank you to @danjlevy and the amazing cast of...  0.502467   0.405147   
12715  I've seen all the charts about the symptoms of...  0.239126   0.665971   
12861  Its 2am. I am having a bad night. Many are hav...  0.404306   0.520929   
13920  Just going to @Target &amp; grocery shopping i...  0.131509   0.812101   
13991  Enough pointless autistic meltdowns. I'm gonna...  0.439615   0.495267   
14670  Things I developed for the first time during t...  0.069944   0.859674   
15070  Donald Trump, the passive-aggressive Sadist So...  0.336334   0.631278   
15100  Reporter Jim @Acosta reads Trump's own words b...  0.065969   0.879181   
15161  One thing people should know: I'm 85, I don’t ...  0.392001   0.549157   
15

In [ ]:
# to add label column
# b = df_messy['twitter4sse_embeddings'].apply(lambda x: clf_xgb.predict([x]))
# b = pd.DataFrame(b)
# b

In [ ]:
# df_messy_prob_label['predicted_label'] = b['twitter4sse_embeddings'].apply(lambda x: x[0])

In [ ]:
# df_messy_prob_label

In [ ]:
# condition where the highest probablity is less than 0.7
condition1 = df_messy_prob_label[['PP_prob', 'PONP_prob', 'UN_prob']].max(axis=1) < 0.7
df_messy_prob_label[condition1]

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.385106   0.528504   
538    As someone who has experienced anxiety and pan...  0.314921   0.607893   
920    When you are having a panic attack and one of ...  0.406203   0.493452   
1137   Heard countries have done/are considering exte...  0.591747   0.347345   
2358   Panic buying, #supplychain shake-ups and compa...  0.453411   0.505183   
3403   My son  19 year old son in Suffolk county NY j...  0.232278   0.653788   
4777   Why did I start watching #pandemic? I feel stu...  0.502414   0.455564   
5451   "I’d be lying if I said that this pandemic did...  0.516846   0.429757   
6587   Three weeks into quarantine and chill, and dam...  0.262277   0.589386   
8069   Society right now is my antisocial dreams. Peo...  0.266329   0.653952   
8083   I know this has been a rough couple of weeks a...  0.439906   0.489478   
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...  0.520397   0.394746   
8408   I was confident on day one we would beat it \n...  0.415107   0.539455   
8632   As someone who has experienced anxiety and pan...  0.613262   0.317045   
8746   The Faint - Paranoiattack https://t.co/glhSnMN...  0.439107   0.494309   
8967   One time I was scared and went to the hospital...  0.247719   0.652935   
9183   Tbh, the daily updates of #Covid19 had given m...  0.311826   0.575428   
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...  0.542123   0.407693   
11390  Emergency Alert — state of Illinois vs. state ...  0.357562   0.566132   
11489  #Coronavirus and anxiety: 'Following the news ...  0.409645   0.500880   
12257  Hi Everyone-\n\nI, like many, have been suffer...  0.472450   0.467107   
12663  Thank you to @danjlevy and the amazing cast of...  0.502467   0.405147   
12715  I've seen all the charts about the symptoms of...  0.239126   0.665971   
12861  Its 2am. I am having a bad night. Many are hav...  0.404306   0.520929   
13991  Enough pointless autistic meltdowns. I'm gonna...  0.439615   0.495267   
15070  Donald Trump, the passive-aggressive Sadist So...  0.336334   0.631278   
15161  One thing people should know: I'm 85, I don’t ...  0.392001   0.549157   
15957  Since my anxiety around #coronavirus subsided,...  0.365769   0.541970   
16511  haven’t tweeted in 6 months &amp; my thing to ...  0.466443   0.461086   

        UN_prob  
381    0.086390  
538    0.077186  
920    0.100346  
1137   0.060908  
2358   0.041406  
3403   0.113935  
4777   0.042022  
5451   0.053398  
6587   0.148337  
8069   0.079720  
8083   0.070617  
8192   0.084857  
8408   0.045438  
8632   0.069693  
8746   0.066584  
8967   0.099347  
9183   0.112746  
9445   0.050184  
11390  0.076306  
11489  0.089475  
12257  0.060443  
12663  0.092386  
12715  0.094904  
12861  0.074764  
13991  0.065118  
15070  0.032388  
15161  0.058842  
15957  0.092261  
16511  0.072471

In [ ]:
# condition where the difference between 2 highest probabilites in less than 0.4
c = df_messy_prob_label[['PP_prob', 'PONP_prob', 'UN_prob']].apply(lambda x: sorted(x, reverse=True), axis=1)
condition2 = c.apply(lambda x: x[0] - x[1]) < 0.4
df_messy_prob_label[condition2]

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.385106   0.528504   
538    As someone who has experienced anxiety and pan...  0.314921   0.607893   
920    When you are having a panic attack and one of ...  0.406203   0.493452   
1137   Heard countries have done/are considering exte...  0.591747   0.347345   
2358   Panic buying, #supplychain shake-ups and compa...  0.453411   0.505183   
4777   Why did I start watching #pandemic? I feel stu...  0.502414   0.455564   
5451   "I’d be lying if I said that this pandemic did...  0.516846   0.429757   
6587   Three weeks into quarantine and chill, and dam...  0.262277   0.589386   
8069   Society right now is my antisocial dreams. Peo...  0.266329   0.653952   
8083   I know this has been a rough couple of weeks a...  0.439906   0.489478   
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...  0.520397   0.394746   
8408   I was confident on day one we would beat it \n...  0.415107   0.539455   
8632   As someone who has experienced anxiety and pan...  0.613262   0.317045   
8746   The Faint - Paranoiattack https://t.co/glhSnMN...  0.439107   0.494309   
9183   Tbh, the daily updates of #Covid19 had given m...  0.311826   0.575428   
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...  0.542123   0.407693   
11390  Emergency Alert — state of Illinois vs. state ...  0.357562   0.566132   
11489  #Coronavirus and anxiety: 'Following the news ...  0.409645   0.500880   
12257  Hi Everyone-\n\nI, like many, have been suffer...  0.472450   0.467107   
12663  Thank you to @danjlevy and the amazing cast of...  0.502467   0.405147   
12861  Its 2am. I am having a bad night. Many are hav...  0.404306   0.520929   
13991  Enough pointless autistic meltdowns. I'm gonna...  0.439615   0.495267   
15070  Donald Trump, the passive-aggressive Sadist So...  0.336334   0.631278   
15161  One thing people should know: I'm 85, I don’t ...  0.392001   0.549157   
15957  Since my anxiety around #coronavirus subsided,...  0.365769   0.541970   
16511  haven’t tweeted in 6 months &amp; my thing to ...  0.466443   0.461086   

        UN_prob  
381    0.086390  
538    0.077186  
920    0.100346  
1137   0.060908  
2358   0.041406  
4777   0.042022  
5451   0.053398  
6587   0.148337  
8069   0.079720  
8083   0.070617  
8192   0.084857  
8408   0.045438  
8632   0.069693  
8746   0.066584  
9183   0.112746  
9445   0.050184  
11390  0.076306  
11489  0.089475  
12257  0.060443  
12663  0.092386  
12861  0.074764  
13991  0.065118  
15070  0.032388  
15161  0.058842  
15957  0.092261  
16511  0.072471

In [ ]:
df_messy_prob_label['cond1'] = np.where(condition1, 1, 0)
df_messy_prob_label['cond2'] = np.where(condition2, 1, 0)

<ipython-input-203-1ced394e49c0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['cond1'] = np.where(condition1, 1, 0)
<ipython-input-203-1ced394e49c0>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_messy_prob_label['cond2'] = np.where(condition2, 1, 0)


In [ ]:
df_messy_prob_label

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.385106   0.528504   
538    As someone who has experienced anxiety and pan...  0.314921   0.607893   
920    When you are having a panic attack and one of ...  0.406203   0.493452   
1137   Heard countries have done/are considering exte...  0.591747   0.347345   
2358   Panic buying, #supplychain shake-ups and compa...  0.453411   0.505183   
2540   Me: Yay! #Saturday!\n\nMy #Anxiety: Hi!\n\nMe:...  0.129380   0.805856   
2859   I wish Boris all the best. Will the media rele...  0.134430   0.779705   
3306   We are all gonna have HELLA trust issues when ...  0.104654   0.842947   
3403   My son  19 year old son in Suffolk county NY j...  0.232278   0.653788   
3763   Has this #coronavirus made us all paranoid? I'...  0.132648   0.838404   
3886   My wife was speaking to me and, after 30s of c...  0.110499   0.804144   
4276   I think I relate to this because coping with a...  0.137271   0.749773   
4777   Why did I start watching #pandemic? I feel stu...  0.502414   0.455564   
5451   "I’d be lying if I said that this pandemic did...  0.516846   0.429757   
6240   watching the perks of being a wallflower over ...  0.150161   0.801156   
6372   I miss the days when I used to be able to scro...  0.172831   0.726412   
6587   Three weeks into quarantine and chill, and dam...  0.262277   0.589386   
7326   FYI\nFear of going out of home = Agoraphobia\n...  0.230112   0.708549   
7453   Reason fifty million why it's difficult to be ...  0.136736   0.793286   
7818   Is this #coronavirus-induced shortness of brea...  0.193386   0.728087   
8069   Society right now is my antisocial dreams. Peo...  0.266329   0.653952   
8083   I know this has been a rough couple of weeks a...  0.439906   0.489478   
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...  0.520397   0.394746   
8408   I was confident on day one we would beat it \n...  0.415107   0.539455   
8632   As someone who has experienced anxiety and pan...  0.613262   0.317045   
8746   The Faint - Paranoiattack https://t.co/glhSnMN...  0.439107   0.494309   
8967   One time I was scared and went to the hospital...  0.247719   0.652935   
9120   you know quarantine’s got you depressed af whe...  0.193981   0.717117   
9122   I think I'm going to only focus on local news ...  0.139773   0.756136   
9183   Tbh, the daily updates of #Covid19 had given m...  0.311826   0.575428   
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...  0.542123   0.407693   
9729   Breaking your addiction to #BreakingNews - "It...  0.077591   0.862354   
10358  BBC News - Coronavirus and anxiety: 'Following...  0.130406   0.767828   
10651  I dont know if this is PTSD... but anytime i s...  0.118788   0.801977   
10790  I'm ridiculously chill in emergency situations...  0.143386   0.762705   
11390  Emergency Alert — state of Illinois vs. state ...  0.357562   0.566132   
11489  #Coronavirus and anxiety: 'Following the news ...  0.409645   0.500880   
11563  Anyone else find themselves having little pani...  0.155345   0.799199   
11810  I've just discovered this if you are a #vulner...  0.201408   0.755290   
12257  Hi Everyone-\n\nI, like many, have been suffer...  0.472450   0.467107   
12663  Thank you to @danjlevy and the amazing cast of...  0.502467   0.405147   
12715  I've seen all the charts about the symptoms of...  0.239126   0.665971   
12861  Its 2am. I am having a bad night. Many are hav...  0.404306   0.520929   
13920  Just going to @Target &amp; grocery shopping i...  0.131509   0.812101   
13991  Enough pointless autistic meltdowns. I'm gonna...  0.439615   0.495267   
14670  Things I developed for the first time during t...  0.069944   0.859674   
15070  Donald Trump, the passive-aggressive Sadist So...  0.336334   0.631278   
15100  Reporter Jim @Acosta reads Trump's own words b...  0.065969   0.879181   
15161  One thing people should know: I'm 85, I don’t ...  0.392001   0.549157   
15

In [ ]:
df_discrepancy = df_messy_prob_label[condition1 | condition2] # Equivalent to - df_messy_prob_label[(df_messy_prob_label['cond1'] == 1) | (df_messy_prob_label['cond2'] == 1)]
df_discrepancy

text   PP_prob  PONP_prob  \
381    NEWS! Conquer Anxiety, Stress and Panic Attack...  0.385106   0.528504   
538    As someone who has experienced anxiety and pan...  0.314921   0.607893   
920    When you are having a panic attack and one of ...  0.406203   0.493452   
1137   Heard countries have done/are considering exte...  0.591747   0.347345   
2358   Panic buying, #supplychain shake-ups and compa...  0.453411   0.505183   
3403   My son  19 year old son in Suffolk county NY j...  0.232278   0.653788   
4777   Why did I start watching #pandemic? I feel stu...  0.502414   0.455564   
5451   "I’d be lying if I said that this pandemic did...  0.516846   0.429757   
6587   Three weeks into quarantine and chill, and dam...  0.262277   0.589386   
8069   Society right now is my antisocial dreams. Peo...  0.266329   0.653952   
8083   I know this has been a rough couple of weeks a...  0.439906   0.489478   
8192   #COVID19 #Boris on #ShakingHands - Im shaking ...  0.520397   0.394746   
8408   I was confident on day one we would beat it \n...  0.415107   0.539455   
8632   As someone who has experienced anxiety and pan...  0.613262   0.317045   
8746   The Faint - Paranoiattack https://t.co/glhSnMN...  0.439107   0.494309   
8967   One time I was scared and went to the hospital...  0.247719   0.652935   
9183   Tbh, the daily updates of #Covid19 had given m...  0.311826   0.575428   
9445   #coronavirus News Alert: Dr. Vladimir Zelenko,...  0.542123   0.407693   
11390  Emergency Alert — state of Illinois vs. state ...  0.357562   0.566132   
11489  #Coronavirus and anxiety: 'Following the news ...  0.409645   0.500880   
12257  Hi Everyone-\n\nI, like many, have been suffer...  0.472450   0.467107   
12663  Thank you to @danjlevy and the amazing cast of...  0.502467   0.405147   
12715  I've seen all the charts about the symptoms of...  0.239126   0.665971   
12861  Its 2am. I am having a bad night. Many are hav...  0.404306   0.520929   
13991  Enough pointless autistic meltdowns. I'm gonna...  0.439615   0.495267   
15070  Donald Trump, the passive-aggressive Sadist So...  0.336334   0.631278   
15161  One thing people should know: I'm 85, I don’t ...  0.392001   0.549157   
15957  Since my anxiety around #coronavirus subsided,...  0.365769   0.541970   
16511  haven’t tweeted in 6 months &amp; my thing to ...  0.466443   0.461086   

        UN_prob  cond1  cond2  
381    0.086390      1      1  
538    0.077186      1      1  
920    0.100346      1      1  
1137   0.060908      1      1  
2358   0.041406      1      1  
3403   0.113935      1      0  
4777   0.042022      1      1  
5451   0.053398      1      1  
6587   0.148337      1      1  
8069   0.079720      1      1  
8083   0.070617      1      1  
8192   0.084857      1      1  
8408   0.045438      1      1  
8632   0.069693      1      1  
8746   0.066584      1      1  
8967   0.099347      1      0  
9183   0.112746      1      1  
9445   0.050184      1      1  
11390  0.076306      1      1  
11489  0.089475      1      1  
12257  0.060443      1      1  
12663  0.092386      1      1  
12715  0.094904      1      0  
12861  0.074764      1      1  
13991  0.065118      1      1  
15070  0.032388      1      1  
15161  0.058842      1      1  
15957  0.092261      1      1  
16511  0.072471      1      1

In [ ]:
df_discrepancy.to_csv('160_emb_liwc_2features_discrepancy.csv')